<?php

declare(strict_types=1);

namespace BKuhl\BibleCSB\Book;

use BKuhl\BibleCSB\Book;
use BKuhl\BibleCSB\Testament;

class FirstChronicles extends Book
{
    public const ABBREVIATION = '1 Chron';
    public const ID = 13;

    public function testament(): Testament
    {
        return Testament::OLD;
    }

    public function name(): string
    {
        return '1 Chronicles';
    }

    public function position(): int
    {
        return self::ID;
    }

    public function abbreviation(): string
    {
        return self::ABBREVIATION;
    }

    /**
     * @return array<int, array{sections: array<int, string>, verses: array<int, string>, versesToSections: array<int, int>}>
     */
    protected function getChapterData(): array
    {
        return [
            1 => [
                'sections' => [
                    1 => 'From Adam to Abraham',
                    2 => 'Abraham\'s Descendants',
                    3 => 'The Edomites',
                ],
                'verses' => [
                ],
                'versesToSections' => [
                ],
            ],
            2 => [
                'sections' => [
                    1 => 'Israel\'s Sons',
                    2 => 'Judah\'s Descendants',
                ],
                'verses' => [
                ],
                'versesToSections' => [
                ],
            ],
            3 => [
                'sections' => [
                    1 => 'David\'s Descendants',
                    2 => 'Judah\'s Kings',
                    3 => 'David\'s Line after the Exile',
                ],
                'verses' => [
                ],
                'versesToSections' => [
                ],
            ],
            4 => [
                'sections' => [
                    1 => 'Judah\'s Descendants',
                    2 => 'Simeon\'s Descendants',
                ],
                'verses' => [
                    9 => 'Jabez was more honored than his brothers. His mother named him Jabez and said, "I gave birth to him in pain."',
                    10 => 'Jabez called out to the God of Israel, "If only you would bless me, extend my border, let your hand be with me, and keep me from harm, so that I will not experience pain." And God granted his request.',
                    41 => 'These who were recorded by name came in the days of King Hezekiah of Judah, attacked the Hamites\' tents and the Meunites who were found there, and set them apart for destruction, as they are today. Then they settled in their place because there was pasture for their flocks.',
                    42 => 'Now five hundred men from these sons of Simeon went with Pelatiah, Neariah, Rephaiah, and Uzziel, the descendants of Ishi, as their leaders to Mount Seir.',
                    43 => 'They struck down the remnant of the Amalekites who had escaped, and they still live there today.',
                ],
                'versesToSections' => [
                    9 => 1,
                    10 => 1,
                    41 => 2,
                    42 => 2,
                    43 => 2,
                ],
            ],
            5 => [
                'sections' => [
                    1 => 'Reuben\'s Descendants',
                    2 => 'Gad\'s Descendants',
                    3 => 'Half the Tribe of Manasseh',
                ],
                'verses' => [
                    1 => 'These were the sons of Reuben the firstborn of Israel. He was the firstborn, but his birthright was given to the sons of Joseph son of Israel, because Reuben defiled his father\'s bed. He is not listed in the genealogy according to birthright.',
                    2 => 'Although Judah became strong among his brothers and a ruler came from him, the birthright was given to Joseph.',
                    6 => 'Beerah was a leader of the Reubenites, and King Tiglath-pileser of Assyria took him into exile.',
                    7 => 'His relatives by their families as they are recorded in their family records:',
                    8 => 'They settled in Aroer as far as Nebo and Baal-meon.',
                    9 => 'They also settled in the east as far as the edge of the desert that extends to the Euphrates River, because their herds had increased in the land of Gilead.',
                    10 => 'During Saul\'s reign they waged war against the Hagrites, who were defeated by their power. And they lived in their tents throughout the region east of Gilead.',
                    18 => 'The descendants of Reuben and Gad and half the tribe of Manasseh had 44,760 warriors who could serve in the army — men who carried shield and sword, drew the bow, and were trained for war.',
                    19 => 'They waged war against the Hagrites, Jetur, Naphish, and Nodab.',
                    20 => 'They received help against these enemies because they cried out to God in battle, and the Hagrites and all their allies were handed over to them. He was receptive to their prayer because they trusted in him.',
                    21 => 'They captured the Hagrites\' livestock — fifty thousand of their camels, two hundred fifty thousand sheep, and two thousand donkeys — as well as one hundred thousand people.',
                    22 => 'Many of the Hagrites were killed because it was God\'s battle. And they lived there in the Hagrites\' place until the exile.',
                    23 => 'The descendants of half the tribe of Manasseh settled in the land from Bashan to Baal-hermon (that is, Senir or Mount Hermon); they were numerous.',
                    24 => 'These were the heads of their ancestral families: Epher, Ishi, Eliel, Azriel, Jeremiah, Hodaviah, and Jahdiel. They were valiant warriors, famous men, and heads of their ancestral houses.',
                    25 => 'But they were unfaithful to the God of their ancestors. They prostituted themselves with the gods of the nations God had destroyed before them.',
                    26 => 'So the God of Israel roused the spirit of King Pul (that is, Tiglath-pileser ) of Assyria, and he took the Reubenites, Gadites, and half the tribe of Manasseh into exile. He took them to Halah, Habor, Hara, and Gozan\'s river, where they are until today.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    18 => 2,
                    19 => 2,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 3,
                    24 => 3,
                    25 => 3,
                    26 => 3,
                ],
            ],
            6 => [
                'sections' => [
                    1 => 'The Levites',
                    2 => 'The Musicians',
                    3 => 'Aaron\'s Descendants',
                    4 => 'The Settlements of the Levites',
                ],
                'verses' => [
                    31 => 'These are the men David put in charge of the music in the Lord\'s temple after the ark came to rest there.',
                    32 => 'They ministered with song in front of the tabernacle, the tent of meeting, until Solomon built the Lord\'s temple in Jerusalem, and they performed their task according to the regulations given to them.',
                    33 => 'These are the men who served with their sons.',
                    48 => 'Their relatives, the Levites, were assigned to all the service of the tabernacle, God\'s temple.',
                    49 => 'But Aaron and his sons did all the work of the most holy place. They presented the offerings on the altar of burnt offerings and on the altar of incense to make atonement for Israel according to all that Moses the servant of God had commanded.',
                    54 => 'These were the places assigned to Aaron\'s descendants from the Kohathite family for their settlements in their territory, because the first lot was for them.',
                    55 => 'They were given Hebron in the land of Judah and its surrounding pasturelands,',
                    56 => 'but the fields and settlements around the city were given to Caleb son of Jephunneh.',
                    57 => 'Aaron\'s descendants were given:',
                    61 => 'To the rest of the Kohathites, ten towns from half the tribe of Manasseh were assigned by lot.',
                    62 => 'The Gershomites were assigned thirteen towns from the tribes of Issachar, Asher, Naphtali, and Manasseh in Bashan according to their families.',
                    63 => 'The Merarites were assigned by lot twelve towns from the tribes of Reuben, Gad, and Zebulun according to their families.',
                    64 => 'So the Israelites gave these towns and their pasturelands to the Levites.',
                    65 => 'They assigned by lot the towns named above from the tribes of the descendants of Judah, Simeon, and Benjamin.',
                    66 => 'Some of the families of the Kohathites were given towns from the tribe of Ephraim for their territory:',
                    71 => 'The Gershomites received:',
                    77 => 'The rest of the Merarites received:',
                ],
                'versesToSections' => [
                    31 => 2,
                    32 => 2,
                    33 => 2,
                    48 => 3,
                    49 => 3,
                    54 => 4,
                    55 => 4,
                    56 => 4,
                    57 => 4,
                    61 => 4,
                    62 => 4,
                    63 => 4,
                    64 => 4,
                    65 => 4,
                    66 => 4,
                    71 => 4,
                    77 => 4,
                ],
            ],
            7 => [
                'sections' => [
                    1 => 'Issachar\'s Descendants',
                    2 => 'Benjamin\'s Descendants',
                    3 => 'Naphtali\'s Descendants',
                    4 => 'Manasseh\'s Descendants',
                    5 => 'Ephraim\'s Descendants',
                    6 => 'Asher\'s Descendants',
                ],
                'verses' => [
                ],
                'versesToSections' => [
                ],
            ],
            8 => [
                'sections' => [
                    1 => 'Benjamin\'s Descendants',
                ],
                'verses' => [
                ],
                'versesToSections' => [
                ],
            ],
            9 => [
                'sections' => [
                    1 => 'After the Exile',
                    2 => 'Saul\'s Family',
                ],
                'verses' => [
                    1 => 'All Israel was registered in the genealogies that are written in the Book of the Kings of Israel. But Judah was exiled to Babylon because of their unfaithfulness.',
                    2 => 'The first to live in their towns on their own property again were Israelites, priests, Levites, and temple servants.',
                    22 => 'The total number of those chosen to be gatekeepers at the thresholds was 212. They were registered by genealogy in their settlements. David and the seer Samuel had appointed them to their trusted positions.',
                    23 => 'So they and their sons were assigned as guards to the gates of the Lord\'s temple, which had been the tent-temple.',
                    24 => 'The gatekeepers were on the four sides: east, west, north, and south.',
                    25 => 'Their relatives came from their settlements at fixed times to be with them seven days,',
                    26 => 'but the four chief gatekeepers, who were Levites, were entrusted with the rooms and the treasuries of God\'s temple.',
                    27 => 'They spent the night in the vicinity of God\'s temple, because they had guard duty and were in charge of opening it every morning.',
                    28 => 'Some of them were in charge of the utensils used in worship. They would count them when they brought them in and when they took them out.',
                    29 => 'Others were put in charge of the furnishings and all the utensils of the sanctuary, as well as the fine flour, wine, oil, incense, and spices.',
                    30 => 'Some of the priests\' sons mixed the spices.',
                    31 => 'A Levite called Mattithiah, the firstborn of Shallum the Korahite, was entrusted with baking the bread.',
                    32 => 'Some of the Kohathites\' relatives were responsible for preparing the rows of the Bread of the Presence every Sabbath.',
                    33 => 'The singers, the heads of the Levite families, stayed in the temple chambers and were exempt from other tasks because they were on duty day and night.',
                    34 => 'These were the heads of the Levite families, chiefs according to their family records; they lived in Jerusalem.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    22 => 1,
                    23 => 1,
                    24 => 1,
                    25 => 1,
                    26 => 1,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                    30 => 1,
                    31 => 1,
                    32 => 1,
                    33 => 1,
                    34 => 1,
                ],
            ],
            10 => [
                'sections' => [
                    1 => 'The Death of Saul and His Sons',
                ],
                'verses' => [
                    1 => 'The Philistines fought against Israel, and Israel\'s men fled from them. Many were killed on Mount Gilboa.',
                    2 => 'The Philistines pursued Saul and his sons and killed his sons Jonathan, Abinadab, and Malchishua.',
                    3 => 'When the battle intensified against Saul, the archers spotted him and severely wounded him.',
                    4 => 'Then Saul said to his armor-bearer, "Draw your sword and run me through with it, or these uncircumcised men will come and torture me." But his armor-bearer would not do it because he was terrified. Then Saul took his sword and fell on it.',
                    5 => 'When his armor-bearer saw that Saul was dead, he also fell on his own sword and died.',
                    6 => 'So Saul and his three sons died — his whole house died together.',
                    7 => 'When all the men of Israel in the valley saw that the army had fled and that Saul and his sons were dead, they abandoned their cities and fled. So the Philistines came and settled in them.',
                    8 => 'The next day when the Philistines came to strip the slain, they found Saul and his sons dead on Mount Gilboa.',
                    9 => 'They stripped Saul, cut off his head, took his armor, and sent messengers throughout the land of the Philistines to spread the good news to their idols and the people.',
                    10 => 'Then they put his armor in the temple of their gods and hung his skull in the temple of Dagon.',
                    11 => 'When all Jabesh-gilead heard of everything the Philistines had done to Saul,',
                    12 => 'all their brave men set out and retrieved the body of Saul and the bodies of his sons and brought them to Jabesh. They buried their bones under the oak in Jabesh and fasted seven days.',
                    13 => 'Saul died for his unfaithfulness to the Lord because he did not keep the Lord\'s word. He even consulted a medium for guidance,',
                    14 => 'but he did not inquire of the Lord. So the put him to death and turned the kingdom over to David son of Jesse.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                ],
            ],
            11 => [
                'sections' => [
                    1 => 'David\'s Anointing as King',
                    2 => 'David\'s Capture of Jerusalem',
                    3 => 'Exploits of David\'s Warriors',
                ],
                'verses' => [
                    1 => 'All Israel came together to David at Hebron and said, "Here we are, your own flesh and blood.',
                    2 => 'Even previously when Saul was king, you were leading Israel out to battle and bringing us back. The your God also said to you, \'You will shepherd my people Israel, and you will be ruler over my people Israel.\' "',
                    3 => 'So all the elders of Israel came to the king at Hebron. David made a covenant with them at Hebron in the Lord\'s presence, and they anointed David king over Israel, in keeping with the Lord\'s word through Samuel.',
                    4 => 'David and all Israel marched to Jerusalem (that is, Jebus); the Jebusites who inhabited the land were there.',
                    5 => 'The inhabitants of Jebus said to David, "You will never get in here." Yet David did capture the stronghold of Zion, that is, the city of David.',
                    6 => 'David said, "Whoever is the first to kill a Jebusite will become chief commander." Joab son of Zeruiah went up first, so he became the chief.',
                    7 => 'Then David took up residence in the stronghold; therefore, it was called the city of David.',
                    8 => 'He built up the city all the way around, from the supporting terraces to the surrounding parts, and Joab restored the rest of the city.',
                    9 => 'David steadily grew more powerful, and the Lord of Armies was with him.',
                    10 => 'The following were the chiefs of David\'s warriors who, together with all Israel, strongly supported him in his reign to make him king according to the Lord\'s word about Israel.',
                    11 => 'This is the list of David\'s warriors:',
                    12 => 'After him, Eleazar son of Dodo the Ahohite was one of the three warriors.',
                    13 => 'He was with David at Pas-dammim when the Philistines had gathered there for battle. There was a portion of a field full of barley, where the troops had fled from the Philistines.',
                    14 => 'But Eleazar and David took their stand in the middle of the field and defended it. They killed the Philistines, and the gave them a great victory.',
                    15 => 'Three of the thirty chief men went down to David, to the rock at the cave of Adullam, while the Philistine army was encamped in Rephaim Valley.',
                    16 => 'At that time David was in the stronghold, and a Philistine garrison was at Bethlehem.',
                    17 => 'David was extremely thirsty and said, "If only someone would bring me water to drink from the well at the city gate of Bethlehem! "',
                    18 => 'So the Three broke through the Philistine camp and drew water from the well at the gate of Bethlehem. They brought it back to David, but he refused to drink it. Instead, he poured it out to the .',
                    19 => 'David said, "I would never do such a thing in the presence of my God! How can I drink the blood of these men who risked their lives? " For they brought it at the risk of their lives. So he would not drink it. Such were the exploits of the three warriors.',
                    20 => 'Abishai, Joab\'s brother, was the leader of the Three. He raised his spear against three hundred men and killed them, gaining a reputation among the Three.',
                    21 => 'He was more honored than the Three and became their commander even though he did not become one of the Three.',
                    22 => 'Benaiah son of Jehoiada was the son of a brave man from Kabzeel, a man of many exploits. Benaiah killed two sons of Ariel of Moab, and he went down into a pit on a snowy day and killed a lion.',
                    23 => 'He also killed an Egyptian who was seven and a half feet tall. Even though the Egyptian had a spear in his hand like a weaver\'s beam, Benaiah went down to him with a staff, snatched the spear out of the Egyptian\'s hand, and then killed him with his own spear.',
                    24 => 'These were the exploits of Benaiah son of Jehoiada, who had a reputation among the three warriors.',
                    25 => 'He was the most honored of the Thirty, but he did not become one of the Three. David put him in charge of his bodyguard.',
                    26 => 'The best soldiers were',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 2,
                    5 => 2,
                    6 => 2,
                    7 => 2,
                    8 => 2,
                    9 => 2,
                    10 => 3,
                    11 => 3,
                    12 => 3,
                    13 => 3,
                    14 => 3,
                    15 => 3,
                    16 => 3,
                    17 => 3,
                    18 => 3,
                    19 => 3,
                    20 => 3,
                    21 => 3,
                    22 => 3,
                    23 => 3,
                    24 => 3,
                    25 => 3,
                    26 => 3,
                ],
            ],
            12 => [
                'sections' => [
                    1 => 'David\'s First Supporters',
                    2 => 'David\'s Soldiers in Hebron',
                ],
                'verses' => [
                    1 => 'The following were the men who came to David at Ziklag while he was still banned from the presence of Saul son of Kish. They were among the warriors who helped him in battle.',
                    2 => 'They were archers who could use either the right or left hand, both to sling stones and shoot arrows from a bow. They were Saul\'s relatives from Benjamin:',
                    8 => 'Some Gadites defected to David at his stronghold in the desert. They were valiant warriors, trained for battle, expert with shield and spear. Their faces were like the faces of lions, and they were as swift as gazelles on the mountains.',
                    14 => 'These Gadites were army commanders; the least of them was a match for a hundred, and the greatest of them for a thousand.',
                    15 => 'These are the men who crossed the Jordan in the first month when it was overflowing all its banks, and put to flight all those in the valleys to the east and to the west.',
                    16 => 'Other Benjaminites and men from Judah also went to David at the stronghold.',
                    17 => 'David went out to meet them and said to them, "If you have come in peace to help me, my heart will be united with you, but if you have come to betray me to my enemies even though my hands have done no wrong, may the God of our ancestors look on it and judge."',
                    18 => 'Then the Spirit enveloped Amasai, chief of the Thirty, and he said:',
                    19 => 'Some Manassites defected to David when he went with the Philistines to fight against Saul. However, they did not help the Philistines because the Philistine rulers sent David away after a discussion. They said, "It will be our heads if he defects to his master Saul."',
                    20 => 'When David went to Ziklag, some men from Manasseh defected to him: Adnah, Jozabad, Jediael, Michael, Jozabad, Elihu, and Zillethai, chiefs of thousands in Manasseh.',
                    21 => 'They helped David against the raiders, for they were all valiant warriors and commanders in the army.',
                    22 => 'At that time, men came day after day to help David until there was a great army, like an army of God.',
                    23 => 'The numbers of the armed troops who came to David at Hebron to turn Saul\'s kingdom over to him, according to the Lord\'s word, were as follows:',
                    38 => 'All these warriors, lined up in battle formation, came to Hebron wholeheartedly determined to make David king over all Israel. All the rest of Israel was also of one mind to make David king.',
                    39 => 'They spent three days there eating and drinking with David, for their relatives had provided for them.',
                    40 => 'In addition, their neighbors from as far away as Issachar, Zebulun, and Naphtali came and brought food on donkeys, camels, mules, and oxen — abundant provisions of flour, fig cakes, raisins, wine and oil, herds, and flocks. Indeed, there was joy in Israel.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    8 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 1,
                    23 => 2,
                    38 => 2,
                    39 => 2,
                    40 => 2,
                ],
            ],
            13 => [
                'sections' => [
                    1 => 'David and the Ark',
                ],
                'verses' => [
                    1 => 'David consulted with all his leaders, the commanders of hundreds and of thousands.',
                    2 => 'Then he said to the whole assembly of Israel, "If it seems good to you, and if this is from the our God, let\'s spread out and send the message to the rest of our relatives in all the districts of Israel, including the priests and Levites in their cities with pasturelands, that they should gather together with us.',
                    3 => 'Then let\'s bring back the ark of our God, for we did not inquire of him in Saul\'s days."',
                    4 => 'Since the proposal seemed right to all the people, the whole assembly agreed to do it.',
                    5 => 'So David assembled all Israel, from the Shihor of Egypt to the entrance of Hamath, to bring the ark of God from Kiriath-jearim.',
                    6 => 'David and all Israel went to Baalah (that is, Kiriath-jearim that belongs to Judah) to take from there the ark of God, which bears the name of the who is enthroned between the cherubim.',
                    7 => 'At Abinadab\'s house they set the ark of God on a new cart. Uzzah and Ahio were guiding the cart.',
                    8 => 'David and all Israel were dancing with all their might before God with songs and with lyres, harps, tambourines, cymbals, and trumpets.',
                    9 => 'When they came to Chidon\'s threshing floor, Uzzah reached out to hold the ark because the oxen had stumbled.',
                    10 => 'Then the Lord\'s anger burned against Uzzah, and he struck him dead because he had reached out to the ark. So he died there in the presence of God.',
                    11 => 'David was angry because of the Lord\'s outburst against Uzzah, so he named that place Outburst Against Uzzah, as it is still named today.',
                    12 => 'David feared God that day and said, "How can I ever bring the ark of God to me? "',
                    13 => 'So David did not bring the ark of God home to the city of David; instead, he diverted it to the house of Obed-edom of Gath.',
                    14 => 'The ark of God remained with Obed-edom\'s family in his house for three months, and the blessed his family and all that he had.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                ],
            ],
            14 => [
                'sections' => [
                    1 => 'God\'s Blessing on David',
                ],
                'verses' => [
                    1 => 'King Hiram of Tyre sent envoys to David, along with cedar logs, stonemasons, and carpenters to build a palace for him.',
                    2 => 'Then David knew that the Lord had established him as king over Israel and that his kingdom had been exalted for the sake of his people Israel.',
                    3 => 'David took more wives in Jerusalem, and he became the father of more sons and daughters.',
                    4 => 'These are the names of the children born to him in Jerusalem: Shammua, Shobab, Nathan, Solomon,',
                    5 => 'Ibhar, Elishua, Elpelet,',
                    6 => 'Nogah, Nepheg, Japhia,',
                    7 => 'Elishama, Beeliada, and Eliphelet.',
                    8 => 'When the Philistines heard that David had been anointed king over all Israel, they all went in search of David; when David heard of this, he went out to face them.',
                    9 => 'Now the Philistines had come and raided in Rephaim Valley,',
                    10 => 'so David inquired of God, "Should I attack the Philistines? Will you hand them over to me? "',
                    11 => 'So the Israelites went up to Baal-perazim, and David defeated the Philistines there. Then David said, "Like a bursting flood, God has used me to burst out against my enemies." Therefore, they named that place The Lord Bursts Out.',
                    12 => 'The Philistines abandoned their idols there, and David ordered that they be burned in the fire.',
                    13 => 'Once again the Philistines raided in the valley.',
                    14 => 'So David again inquired of God, and God answered him, "Do not pursue them directly. Circle around them and attack them opposite the balsam trees.',
                    15 => 'When you hear the sound of marching in the tops of the balsam trees, then go out to battle, for God will have gone out ahead of you to strike down the army of the Philistines."',
                    16 => 'So David did as God commanded him, and they struck down the Philistine army from Gibeon to Gezer.',
                    17 => 'Then David\'s fame spread throughout the lands, and the Lord caused all the nations to be terrified of him.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                ],
            ],
            15 => [
                'sections' => [
                    1 => 'The Ark Comes to Jerusalem',
                ],
                'verses' => [
                    1 => 'David built houses for himself in the city of David, and he prepared a place for the ark of God and pitched a tent for it.',
                    2 => 'Then David said, "No one but the Levites may carry the ark of God, because the has chosen them to carry the ark of the Lord and to minister before him forever."',
                    3 => 'David assembled all Israel at Jerusalem to bring the ark of the Lord to the place he had prepared for it.',
                    4 => 'Then he gathered together the descendants of Aaron and the Levites:',
                    5 => 'From the Kohathites, Uriel the leader and 120 of his relatives;',
                    6 => 'from the Merarites, Asaiah the leader and 220 of his relatives;',
                    7 => 'from the Gershomites, Joel the leader and 130 of his relatives;',
                    8 => 'from the Elizaphanites, Shemaiah the leader and 200 of his relatives;',
                    9 => 'from the Hebronites, Eliel the leader and 80 of his relatives;',
                    10 => 'from the Uzzielites, Amminadab the leader and 112 of his relatives.',
                    11 => 'David summoned the priests Zadok and Abiathar and the Levites Uriel, Asaiah, Joel, Shemaiah, Eliel, and Amminadab.',
                    12 => 'He said to them, "You are the heads of the Levite families. You and your relatives must consecrate yourselves so that you may bring the ark of the Lord God of Israel to the place I have prepared for it.',
                    13 => 'For the Lord our God burst out in anger against us because you Levites were not with us the first time, for we didn\'t inquire of him about the proper procedures."',
                    14 => 'So the priests and the Levites consecrated themselves to bring up the ark of the God of Israel.',
                    15 => 'Then the Levites carried the ark of God the way Moses had commanded according to the word of the Lord: on their shoulders with the poles.',
                    16 => 'Then David told the leaders of the Levites to appoint their relatives as singers and to have them raise their voices with joy accompanied by musical instruments — harps, lyres, and cymbals.',
                    17 => 'So the Levites appointed Heman son of Joel; from his relatives, Asaph son of Berechiah; and from their relatives the Merarites, Ethan son of Kushaiah.',
                    18 => 'With them were their relatives second in rank: Zechariah, Jaaziel, Shemiramoth, Jehiel, Unni, Eliab, Benaiah, Maaseiah, Mattithiah, Eliphelehu, Mikneiah, and the gatekeepers Obed-edom and Jeiel.',
                    19 => 'The singers Heman, Asaph, and Ethan were to sound the bronze cymbals;',
                    20 => 'Zechariah, Aziel, Shemiramoth, Jehiel, Unni, Eliab, Maaseiah, and Benaiah were to play harps according to \'Alamoth\'',
                    21 => 'and Mattithiah, Eliphelehu, Mikneiah, Obed-edom, Jeiel, and Azaziah were to lead the music with lyres according to the \'Sheminith\'.',
                    22 => 'Chenaniah, the leader of the Levites in music, was to direct the music because he was skillful.',
                    23 => 'Berechiah and Elkanah were to be gatekeepers for the ark.',
                    24 => 'The priests, Shebaniah, Joshaphat, Nethanel, Amasai, Zechariah, Benaiah, and Eliezer, were to blow trumpets before the ark of God. Obed-edom and Jehiah were also to be gatekeepers for the ark.',
                    25 => 'David, the elders of Israel, and the commanders of thousands went with rejoicing to bring the ark of the covenant of the Lord from the house of Obed-edom.',
                    26 => 'Because God helped the Levites who were carrying the ark of the covenant of the , with God\'s help, they sacrificed seven bulls and seven rams.',
                    27 => 'Now David was dressed in a robe of fine linen, as were all the Levites who were carrying the ark, as well as the singers and Chenaniah, the music leader of the singers. David also wore a linen ephod.',
                    28 => 'So all Israel brought up the ark of the covenant of the Lord with shouts, the sound of the ram\'s horn, trumpets, and cymbals, and the playing of harps and lyres.',
                    29 => 'As the ark of the covenant of the Lord was entering the city of David, Saul\'s daughter Michal looked down from the window and saw King David leaping and dancing, and she despised him in her heart.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 1,
                    23 => 1,
                    24 => 1,
                    25 => 1,
                    26 => 1,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                ],
            ],
            16 => [
                'sections' => [
                    1 => 'David\'s Psalm of Thanksgiving',
                ],
                'verses' => [
                    1 => 'They brought the ark of God and placed it inside the tent David had pitched for it. Then they offered burnt offerings and fellowship offerings in God\'s presence.',
                    2 => 'When David had finished offering the burnt offerings and the fellowship offerings, he blessed the people in the name of the Lord.',
                    3 => 'Then he distributed to each and every Israelite, both men and women, a loaf of bread, a date cake, and a raisin cake.',
                    4 => 'David appointed some of the Levites to be ministers before the ark of the Lord, to celebrate the Lord God of Israel, and to give thanks and praise to him.',
                    5 => 'Asaph was the chief and Zechariah was second to him. Jeiel, Shemiramoth, Jehiel, Mattithiah, Eliab, Benaiah, Obed-edom, and Jeiel played the harps and lyres, while Asaph sounded the cymbals',
                    6 => 'and the priests Benaiah and Jahaziel blew the trumpets regularly before the ark of the covenant of God.',
                    7 => 'On that day David decreed for the first time that thanks be given to the Lord by Asaph and his relatives:',
                    37 => 'So David left Asaph and his relatives there before the ark of the Lord\'s covenant to minister regularly before the ark according to the daily requirements.',
                    38 => 'He assigned Obed-edom and his sixty-eight relatives. Obed-edom son of Jeduthun and Hosah were to be gatekeepers.',
                    39 => 'David left the priest Zadok and his fellow priests before the tabernacle of the at the high place in Gibeon',
                    40 => 'to offer burnt offerings regularly, morning and evening, to the Lord on the altar of burnt offerings and to do everything that was written in the law of the , which he had commanded Israel to keep.',
                    41 => 'With them were Heman, Jeduthun, and the rest who were chosen and designated by name to give thanks to the Lord — for his faithful love endures forever.',
                    42 => 'Heman and Jeduthun had with them trumpets and cymbals to play and musical instruments of God. Jeduthun\'s sons were at the city gate.',
                    43 => 'Then all the people went home, and David returned home to bless his household.',
                ],
                'versesToSections' => [
                    1 => 0,
                    2 => 0,
                    3 => 0,
                    4 => 0,
                    5 => 0,
                    6 => 0,
                    7 => 1,
                    37 => 1,
                    38 => 1,
                    39 => 1,
                    40 => 1,
                    41 => 1,
                    42 => 1,
                    43 => 1,
                ],
            ],
            17 => [
                'sections' => [
                    1 => 'The \'s Covenant with David',
                    2 => 'David\'s Prayer of Thanksgiving',
                ],
                'verses' => [
                    1 => 'When David had settled into his palace, he said to the prophet Nathan, "Look! I am living in a cedar house while the ark of the Lord\'s covenant is under tent curtains."',
                    2 => 'So Nathan told David, "Do all that is on your mind, for God is with you."',
                    3 => 'But that night the word of God came to Nathan:',
                    4 => '"Go to David my servant and say, \'This is what the Lord says: You are not the one to build me a house to dwell in.',
                    5 => 'From the time I brought Israel out of Egypt until today I have not dwelt in a house; instead, I have moved from one tent site to another, and from one tabernacle location to another.',
                    6 => 'In all my journeys throughout Israel, have I ever spoken a word to even one of the judges of Israel, whom I commanded to shepherd my people, asking: Why haven\'t you built me a house of cedar? \'',
                    7 => '"So now this is what you are to say to my servant David: \'This is what the of Armies says: I took you from the pasture, from tending the flock, to be ruler over my people Israel.',
                    8 => 'I have been with you wherever you have gone, and I have destroyed all your enemies before you. I will make a name for you like that of the greatest on the earth.',
                    9 => 'I will designate a place for my people Israel and plant them, so that they may live there and not be disturbed again. Evildoers will not continue to oppress them as they have done',
                    10 => '" \'Furthermore, I declare to you that the Lord himself will build a house for you.',
                    11 => 'When your time comes to be with your ancestors, I will raise up after you your descendant, who is one of your own sons, and I will establish his kingdom.',
                    12 => 'He is the one who will build a house for me, and I will establish his throne forever.',
                    13 => 'I will be his father, and he will be my son. I will not remove my faithful love from him as I removed it from the one who was before you.',
                    14 => 'I will appoint him over my house and my kingdom forever, and his throne will be established forever.\' "',
                    15 => 'Nathan reported all these words and this entire vision to David.',
                    16 => 'Then King David went in, sat in the Lord\'s presence, and said,',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 2,
                ],
            ],
            18 => [
                'sections' => [
                    1 => 'David\'s Military Campaigns',
                ],
                'verses' => [
                    1 => 'After this, David defeated the Philistines, subdued them, and took Gath and its surrounding villages from Philistine control.',
                    2 => 'He also defeated the Moabites, and they became David\'s subjects and brought tribute.',
                    3 => 'David also defeated King Hadadezer of Zobah at Hamath when he went to establish his control at the Euphrates River.',
                    4 => 'David captured one thousand chariots, seven thousand horsemen, and twenty thousand foot soldiers from him, hamstrung all the horses, and kept a hundred chariots.',
                    5 => 'When the Arameans of Damascus came to assist King Hadadezer of Zobah, David struck down twenty-two thousand Aramean men.',
                    6 => 'Then he placed garrisons in Aram of Damascus, and the Arameans became David\'s subjects and brought tribute. The made David victorious wherever he went.',
                    7 => 'David took the gold shields carried by Hadadezer\'s officers and brought them to Jerusalem.',
                    8 => 'From Tibhath and Cun, Hadadezer\'s cities, David also took huge quantities of bronze, from which Solomon made the bronze basin, the pillars, and the bronze articles.',
                    9 => 'When King Tou of Hamath heard that David had defeated the entire army of King Hadadezer of Zobah,',
                    10 => 'he sent his son Hadoram to King David to greet him and to congratulate him because David had fought against Hadadezer and defeated him, for Tou and Hadadezer had fought many wars. Hadoram brought all kinds of gold, silver, and bronze items.',
                    11 => 'King David also dedicated these to the Lord, along with the silver and gold he had carried off from all the nations — from Edom, Moab, the Ammonites, the Philistines, and the Amalekites.',
                    12 => 'Abishai son of Zeruiah struck down eighteen thousand Edomites in the Salt Valley.',
                    13 => 'He put garrisons in Edom, and all the Edomites were subject to David. The made David victorious wherever he went.',
                    14 => 'So David reigned over all Israel, administering justice and righteousness for all his people.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                ],
            ],
            19 => [
                'sections' => [
                    1 => 'War with the Ammonites',
                ],
                'verses' => [
                    1 => 'Some time later, King Nahash of the Ammonites died, and his son became king in his place.',
                    2 => 'So David sent messengers to console him concerning his father. However, when David\'s emissaries arrived in the land of the Ammonites to console him,',
                    3 => 'the Ammonite leaders said to Hanun, "Just because David has sent men with condolences for you, do you really believe he\'s showing respect for your father? Instead, haven\'t his emissaries come in order to scout out, overthrow, and spy on the land? "',
                    4 => 'So Hanun took David\'s emissaries, shaved them, cut their clothes in half at the hips, and sent them away.',
                    5 => 'It was reported to David about his men, so he sent messengers to meet them, since the men were deeply humiliated. The king said, "Stay in Jericho until your beards grow back; then return."',
                    6 => 'When the Ammonites realized they had made themselves repulsive to David, Hanun and the Ammonites sent thirty-eight tons of silver to hire chariots and horsemen from Aram-naharaim, Aram-maacah, and Zobah.',
                    7 => 'They hired thirty-two thousand chariots and the king of Maacah with his army, who came and camped near Medeba. The Ammonites also came together from their cities for the battle.',
                    8 => 'David heard about this and sent Joab and all the elite troops.',
                    9 => 'The Ammonites marched out and lined up in battle formation at the entrance of the city while the kings who had come were in the field by themselves.',
                    10 => 'When Joab saw that there was a battle line in front of him and another behind him, he chose some of Israel\'s finest young men and lined up in formation to engage the Arameans.',
                    11 => 'He placed the rest of the forces under the command of his brother Abishai. They lined up in formation to engage the Ammonites.',
                    12 => '"If the Arameans are too strong for me," Joab said, "then you\'ll be my help. However, if the Ammonites are too strong for you, I\'ll help you.',
                    13 => 'Be strong! Let\'s prove ourselves strong for our people and for the cities of our God. May the Lord\'s will be done."',
                    14 => 'Joab and the people with him approached the Arameans for battle, and they fled before him.',
                    15 => 'When the Ammonites saw that the Arameans had fled, they likewise fled before Joab\'s brother Abishai and entered the city. Then Joab went to Jerusalem.',
                    16 => 'When the Arameans realized that they had been defeated by Israel, they sent messengers to summon the Arameans who were beyond the Euphrates River. They were led by Shophach, the commander of Hadadezer\'s army.',
                    17 => 'When this was reported to David, he gathered all Israel and crossed the Jordan. He came up to the Arameans and lined up against them. When David lined up to engage them, they fought against him.',
                    18 => 'But the Arameans fled before Israel, and David killed seven thousand of their charioteers and forty thousand foot soldiers. He also killed Shophach, commander of the army.',
                    19 => 'When Hadadezer\'s subjects saw that they had been defeated by Israel, they made peace with David and became his subjects. After this, the Arameans were never willing to help the Ammonites again.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                ],
            ],
            20 => [
                'sections' => [
                    1 => 'Capture of the City of Rabbah',
                    2 => 'The Philistine Giants',
                ],
                'verses' => [
                    1 => 'In the spring when kings march out to war, Joab led the army and destroyed the Ammonites\' land. He came to Rabbah and besieged it, but David remained in Jerusalem. Joab attacked Rabbah and demolished it.',
                    2 => 'Then David took the crown from the head of their king, and it was placed on David\'s head. He found that the crown weighed seventy-five pounds of gold, and there was a precious stone in it. In addition, David took away a large quantity of plunder from the city.',
                    3 => 'He brought out the people who were in it and put them to work with saws, iron picks, and axes. David did the same to all the Ammonite cities. Then he and all his troops returned to Jerusalem.',
                    4 => 'After this, a war broke out with the Philistines at Gezer. At that time Sibbecai the Hushathite killed Sippai, a descendant of the Rephaim, and the Philistines were subdued.',
                    5 => 'Once again there was a battle with the Philistines, and Elhanan son of Jair killed Lahmi the brother of Goliath of Gath. The shaft of his spear was like a weaver\'s beam.',
                    6 => 'There was still another battle at Gath where there was a man of extraordinary stature with six fingers on each hand and six toes on each foot — twenty-four in all. He, too, was descended from the giant.',
                    7 => 'When he taunted Israel, Jonathan son of David\'s brother Shimei killed him.',
                    8 => 'These were the descendants of the giant in Gath killed by David and his soldiers.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 2,
                    5 => 2,
                    6 => 2,
                    7 => 2,
                    8 => 2,
                ],
            ],
            21 => [
                'sections' => [
                    1 => 'David\'s Military Census',
                    2 => 'David\'s Punishment',
                    3 => 'David\'s Altar',
                ],
                'verses' => [
                    1 => 'Satan rose up against Israel and incited David to count the people of Israel.',
                    2 => 'So David said to Joab and the commanders of the troops, "Go and count Israel from Beer-sheba to Dan and bring a report to me so I can know their number."',
                    3 => 'Joab replied, "May the Lord multiply the number of his people a hundred times over! My lord the king, aren\'t they all my lord\'s servants? Why does my lord want to do this? Why should he bring guilt on Israel? "',
                    4 => 'Yet the king\'s order prevailed over Joab. So Joab left and traveled throughout Israel and then returned to Jerusalem.',
                    5 => 'Joab gave the total troop registration to David. In all Israel there were one million one hundred thousand armed men and in Judah itself four hundred seventy thousand armed men.',
                    6 => 'But he did not include Levi and Benjamin in the count because the king\'s command was detestable to him.',
                    7 => 'This command was also evil in God\'s sight, so he afflicted Israel.',
                    8 => 'David said to God, "I have sinned greatly because I have done this thing. Now, please take away your servant\'s guilt, for I\'ve been very foolish."',
                    9 => 'Then the Lord instructed Gad, David\'s seer,',
                    10 => '"Go and say to David, \'This is what the Lord says: I am offering you three choices. Choose one of them for yourself, and I will do it to you.\' "',
                    11 => 'So Gad went to David and said to him, "This is what the Lord says: \'Take your choice:',
                    12 => 'three years of famine, or three months of devastation by your foes with the sword of your enemy overtaking you, or three days of the sword of the Lord — a plague on the land, the angel of the Lord bringing destruction to the whole territory of Israel.\' Now decide what answer I should take back to the one who sent me."',
                    13 => 'David answered Gad, "I\'m in anguish. Please, let me fall into the \'s hands because his mercies are very great, but don\'t let me fall into human hands."',
                    14 => 'So the Lord sent a plague on Israel, and seventy thousand Israelite men died.',
                    15 => 'Then God sent an angel to Jerusalem to destroy it, but when the angel was about to destroy the city, the Lord looked, relented concerning the destruction, and said to the angel who was destroying the people, "Enough, withdraw your hand now! " The angel of the Lord was then standing at the threshing floor of Ornan the Jebusite.',
                    16 => 'When David looked up and saw the angel of the Lord standing between earth and heaven, with his drawn sword in his hand stretched out over Jerusalem, David and the elders, covered in sackcloth, fell facedown.',
                    17 => 'David said to God, "Wasn\'t I the one who gave the order to count the people? I am the one who has sinned and acted very wickedly. But these sheep, what have they done? Lord my God, please let your hand be against me and against my father\'s family, but don\'t let the plague be against your people."',
                    18 => 'So the angel of the Lord ordered Gad to tell David to go and set up an altar to the Lord on the threshing floor of Ornan the Jebusite.',
                    19 => 'David went up at Gad\'s command spoken in the name of the Lord.',
                    20 => 'Ornan was threshing wheat when he turned and saw the angel. His four sons, who were with him, hid.',
                    21 => 'David came to Ornan, and when Ornan looked and saw David, he left the threshing floor and bowed to David with his face to the ground.',
                    22 => 'Then David said to Ornan, "Give me this threshing-floor plot so that I may build an altar to the on it. Give it to me for the full price, so the plague on the people may be stopped."',
                    23 => 'Ornan said to David, "Take it! My lord the king may do whatever he wants. See, I give the oxen for the burnt offerings, the threshing sledges for the wood, and the wheat for the grain offering — I give it all."',
                    24 => 'King David answered Ornan, "No, I insist on paying the full price, for I will not take for the what belongs to you or offer burnt offerings that cost me nothing."',
                    25 => 'So David gave Ornan fifteen pounds of gold for the plot.',
                    26 => 'He built an altar to the Lord there and offered burnt offerings and fellowship offerings. He called on the Lord, and he answered him with fire from heaven on the altar of burnt offering.',
                    27 => 'Then the spoke to the angel, and he put his sword back into its sheath.',
                    28 => 'At that time, David offered sacrifices there when he saw that the Lord answered him at the threshing floor of Ornan the Jebusite.',
                    29 => 'The tabernacle of the Lord, which Moses made in the wilderness, and the altar of burnt offering were at the high place in Gibeon,',
                    30 => 'but David could not go before it to inquire of God, because he was terrified of the sword of the Lord\'s angel.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 2,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 3,
                    19 => 3,
                    20 => 3,
                    21 => 3,
                    22 => 3,
                    23 => 3,
                    24 => 3,
                    25 => 3,
                    26 => 3,
                    27 => 3,
                    28 => 3,
                    29 => 3,
                    30 => 3,
                ],
            ],
            22 => [
                'sections' => [
                    1 => 'David\'s Preparations for the Temple',
                ],
                'verses' => [
                    1 => 'Then David said, "This is the house of the God, and this is the altar of burnt offering for Israel."',
                    2 => 'So David gave orders to gather the resident aliens that were in the land of Israel, and he appointed stonecutters to cut finished stones for building God\'s house.',
                    3 => 'David supplied a great deal of iron to make the nails for the doors of the gates and for the fittings, together with an immeasurable quantity of bronze,',
                    4 => 'and innumerable cedar logs because the Sidonians and Tyrians had brought a large quantity of cedar logs to David.',
                    5 => 'David said, "My son Solomon is young and inexperienced, and the house that is to be built for the must be exceedingly great and famous and glorious in all the lands. Therefore, I will make provision for it." So David made lavish preparations for it before his death.',
                    6 => 'Then he summoned his son Solomon and charged him to build a house for the Lord God of Israel.',
                    7 => '"My son," David said to Solomon, "It was in my heart to build a house for the name of the my God,',
                    8 => 'but the word of the Lord came to me: \'You have shed much blood and waged great wars. You are not to build a house for my name because you have shed so much blood on the ground before me.',
                    9 => 'But a son will be born to you; he will be a man of rest. I will give him rest from all his surrounding enemies, for his name will be Solomon, and I will give peace and quiet to Israel during his reign.',
                    10 => 'He is the one who will build a house for my name. He will be my son, and I will be his father. I will establish the throne of his kingdom over Israel forever.\'',
                    11 => '"Now, my son, may the Lord be with you, and may you succeed in building the house of the Lord your God, as he said about you.',
                    12 => 'Above all, may the Lord give you insight and understanding when he puts you in charge of Israel so that you may keep the law of the Lord your God.',
                    13 => 'Then you will succeed if you carefully follow the statutes and ordinances the Lord commanded Moses for Israel. Be strong and courageous. Don\'t be afraid or discouraged.',
                    14 => '"Notice I have taken great pains to provide for the house of the Lord — 3,775 tons of gold, 37,750 tons of silver, and bronze and iron that can\'t be weighed because there is so much of it. I have also provided timber and stone, but you will need to add more to them.',
                    15 => 'You also have many workers: stonecutters, masons, carpenters, and people skilled in every kind of work',
                    16 => 'in gold, silver, bronze, and iron — beyond number. Now begin the work, and may the be with you."',
                    17 => 'Then David ordered all the leaders of Israel to help his son Solomon:',
                    18 => '"The your God is with you, isn\'t he? And hasn\'t he given you rest on every side? For he has handed the land\'s inhabitants over to me, and the land has been subdued before the and his people.',
                    19 => 'Now determine in your mind and heart to seek the Lord your God. Get started building the Lord God\'s sanctuary so that you may bring the ark of the Lord\'s covenant and the holy articles of God to the temple that is to be built for the name of the Lord."',
                ],
                'versesToSections' => [
                    1 => 0,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                ],
            ],
            23 => [
                'sections' => [
                    1 => 'The Divisions of the Levites',
                ],
                'verses' => [
                    1 => 'When David was old and full of days, he installed his son Solomon as king over Israel.',
                    2 => 'Then he gathered all the leaders of Israel, the priests, and the Levites.',
                    3 => 'The Levites thirty years old or more were counted; the total number of men was thirty-eight thousand by headcount.',
                    4 => '"Of these," David said, "twenty-four thousand are to be in charge of the work on the Lord\'s temple, six thousand are to be officers and judges,',
                    5 => 'four thousand are to be gatekeepers, and four thousand are to praise the Lord with the instruments that I have made for worship."',
                    6 => 'Then David divided them into divisions according to Levi\'s sons: Gershom, Kohath, and Merari.',
                    13 => 'Aaron, along with his descendants, was set apart forever to consecrate the most holy things, to burn incense in the presence of the Lord, to minister to him, and to pronounce blessings in his name forever.',
                    14 => 'As for Moses the man of God, his sons were named among the tribe of Levi.',
                    24 => 'These were the descendants of Levi by their ancestral families — the family heads, according to their registration by name in the headcount — twenty years old or more, who worked in the service of the Lord\'s temple.',
                    25 => 'For David said, "The Lord God of Israel has given rest to his people, and he has come to stay in Jerusalem forever.',
                    26 => 'Also, the Levites no longer need to carry the tabernacle or any of the equipment for its service" —',
                    27 => 'for according to the last words of David, the Levites twenty years old or more were to be counted —',
                    28 => '"but their duty will be to assist the descendants of Aaron with the service of the \'s temple, being responsible for the courts and the chambers, the purification of all the holy things, and the work of the service of God\'s temple —',
                    29 => 'as well as the rows of the Bread of the Presence, the fine flour for the grain offering, the wafers of unleavened bread, the baking, the mixing, and all measurements of volume and length.',
                    30 => 'They are also to stand every morning to give thanks and praise to the Lord, and likewise in the evening.',
                    31 => 'Whenever burnt offerings are offered to the Lord on the Sabbaths, New Moons, and appointed festivals, they are to offer them regularly in the Lord\'s presence according to the number prescribed for them.',
                    32 => 'They are to carry out their responsibilities for the tent of meeting, for the holy place, and for their relatives, the descendants of Aaron, in the service of the Lord\'s temple."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    13 => 1,
                    14 => 1,
                    24 => 1,
                    25 => 1,
                    26 => 1,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                    30 => 1,
                    31 => 1,
                    32 => 1,
                ],
            ],
            24 => [
                'sections' => [
                    1 => 'The Divisions of the Priests',
                    2 => 'The Rest of the Levites',
                ],
                'verses' => [
                    1 => 'The divisions of the descendants of Aaron were as follows: Aaron\'s sons were Nadab, Abihu, Eleazar, and Ithamar.',
                    2 => 'But Nadab and Abihu died before their father, and they had no sons, so Eleazar and Ithamar served as priests.',
                    3 => 'Together with Zadok from the descendants of Eleazar and Ahimelech from the descendants of Ithamar, David divided them according to the assigned duties of their service.',
                    4 => 'Since more leaders were found among Eleazar\'s descendants than Ithamar\'s, they were divided accordingly: sixteen heads of ancestral families were from Eleazar\'s descendants, and eight heads of ancestral families were from Ithamar\'s.',
                    5 => 'They were assigned by lot, for there were officers of the sanctuary and officers of God among both Eleazar\'s and Ithamar\'s descendants.',
                    6 => 'The secretary, Shemaiah son of Nethanel, a Levite, recorded them in the presence of the king and the officers, the priest Zadok, Ahimelech son of Abiathar, and the heads of families of the priests and the Levites. One ancestral family was taken for Eleazar, and then one for Ithamar.',
                    19 => 'These had their assigned duties for service when they entered the Lord\'s temple, according to their regulations, which they received from their ancestor Aaron, as the God of Israel had commanded him.',
                    30 => 'Those were the descendants of the Levites according to their ancestral families.',
                    31 => 'They also cast lots the same way as their relatives the descendants of Aaron did in the presence of King David, Zadok, Ahimelech, and the heads of the families of the priests and Levites — the family heads and their younger brothers alike.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    19 => 1,
                    30 => 2,
                    31 => 2,
                ],
            ],
            25 => [
                'sections' => [
                    1 => 'The Levitical Musicians',
                ],
                'verses' => [
                    1 => 'David and the officers of the army also set apart some of the sons of Asaph, Heman, and Jeduthun, who were to prophesy accompanied by lyres, harps, and cymbals. This is the list of the men who performed their service:',
                    6 => 'All these men were under their own fathers\' authority for the music in the \'s temple, with cymbals, harps, and lyres for the service of God\'s temple. Asaph, Jeduthun, and Heman were under the king\'s authority.',
                    7 => 'They numbered 288 together with their relatives who were all trained and skillful in music for the Lord.',
                    8 => 'They cast lots for their duties, young and old alike, teacher as well as pupil.',
                ],
                'versesToSections' => [
                    1 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                ],
            ],
            26 => [
                'sections' => [
                    1 => 'The Levitical Gatekeepers',
                    2 => 'The Levitical Treasurers and Other Officials',
                ],
                'verses' => [
                    1 => 'The following were the divisions of the gatekeepers:',
                    12 => 'These divisions of the gatekeepers, under their leading men, had duties for ministering in the \'s temple, just as their relatives did.',
                    13 => 'They cast lots for each temple gate according to their ancestral families, young and old alike.',
                    14 => 'The lot for the east gate fell to Shelemiah. They also cast lots for his son Zechariah, an insightful counselor, and his lot came out for the north gate.',
                    15 => 'Obed-edom\'s was the south gate, and his sons\' lot was for the storehouses;',
                    16 => 'There were guards stationed at every watch.',
                    17 => 'There were six Levites each day on the east, four each day on the north, four each day on the south, and two pair at the storehouses.',
                    18 => 'As for the court on the west, there were four at the highway and two at the court.',
                    19 => 'Those were the divisions of the gatekeepers from the descendants of the Korahites and Merarites.',
                    20 => 'From the Levites, Ahijah was in charge of the treasuries of God\'s temple and the treasuries of what had been dedicated.',
                    21 => 'From the sons of Ladan, who were the descendants of the Gershonites through Ladan and were the family heads belonging to Ladan the Gershonite: Jehieli.',
                    22 => 'The sons of Jehieli, Zetham and his brother Joel, were in charge of the treasuries of the Lord\'s temple.',
                    23 => 'From the Amramites, the Izharites, the Hebronites, and the Uzzielites:',
                    24 => 'Shebuel, a descendant of Moses\'s son Gershom, was the officer in charge of the treasuries.',
                    25 => 'His relatives through Eliezer: his son Rehabiah, his son Jeshaiah, his son Joram, his son Zichri, and his son Shelomith.',
                    26 => 'This Shelomith and his relatives were in charge of all the treasuries of what had been dedicated by King David, by the family heads who were the commanders of thousands and of hundreds, and by the army commanders.',
                    27 => 'They dedicated part of the plunder from their battles for the repair of the Lord\'s temple.',
                    28 => 'All that the seer Samuel, Saul son of Kish, Abner son of Ner, and Joab son of Zeruiah had dedicated, along with everything else that had been dedicated, were in the care of Shelomith and his relatives.',
                    29 => 'From the Izrahites: Chenaniah and his sons had duties outside the temple as officers and judges over Israel.',
                    30 => 'From the Hebronites: Hashabiah and his relatives, 1,700 capable men, had assigned duties in Israel west of the Jordan for all the work of the and for the service of the king.',
                    31 => 'From the Hebronites: Jerijah was the head of the Hebronites, according to the family records of his ancestors. A search was made in the fortieth year of David\'s reign and strong, capable men were found among them at Jazer in Gilead.',
                    32 => 'There were among Jerijah\'s relatives 2,700 capable men who were family heads. King David appointed them over the Reubenites, the Gadites, and half the tribe of Manasseh as overseers in every matter relating to God and the king.',
                ],
                'versesToSections' => [
                    1 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 2,
                    24 => 2,
                    25 => 2,
                    26 => 2,
                    27 => 2,
                    28 => 2,
                    29 => 2,
                    30 => 2,
                    31 => 2,
                    32 => 2,
                ],
            ],
            27 => [
                'sections' => [
                    1 => 'David\'s Secular Officials',
                ],
                'verses' => [
                    1 => 'This is the list of the Israelites, the family heads, the commanders of thousands and the commanders of hundreds, and their officers who served the king in every matter to do with the divisions that were on rotated military duty each month throughout the year. There were 24,000 in each division:',
                    23 => 'David didn\'t count the men aged twenty or under, for the Lord had said he would make Israel as numerous as the stars of the sky.',
                    24 => 'Joab son of Zeruiah began to count them, but he didn\'t complete it. There was wrath against Israel because of this census, and the number was not entered in the Historical Record of King David.',
                    32 => 'David\'s uncle Jonathan was a counselor; he was a man of understanding and a scribe. Jehiel son of Hachmoni attended the king\'s sons.',
                    33 => 'Ahithophel was the king\'s counselor. Hushai the Archite was the king\'s friend.',
                    34 => 'After Ahithophel came Jehoiada son of Benaiah, then Abiathar. Joab was the commander of the king\'s army.',
                ],
                'versesToSections' => [
                    1 => 1,
                    23 => 1,
                    24 => 1,
                    32 => 1,
                    33 => 1,
                    34 => 1,
                ],
            ],
            28 => [
                'sections' => [
                    1 => 'David Commissions Solomon to Build the Temple',
                ],
                'verses' => [
                    1 => 'David assembled all the leaders of Israel in Jerusalem: the leaders of the tribes, the leaders of the divisions in the king\'s service, the commanders of thousands and the commanders of hundreds, and the officials in charge of all the property and cattle of the king and his sons, along with the court officials, the fighting men, and all the best soldiers.',
                    2 => 'Then King David rose to his feet and said, "Listen to me, my brothers and my people. It was in my heart to build a house as a resting place for the ark of the Lord\'s covenant and as a footstool for our God. I had made preparations to build,',
                    3 => 'but God said to me, \'You are not to build a house for my name because you are a man of war and have shed blood.\'',
                    4 => '"Yet the Lord God of Israel chose me out of all my father\'s family to be king over Israel forever. For he chose Judah as leader, and from the house of Judah, my father\'s family, and from my father\'s sons, he was pleased to make me king over all Israel.',
                    5 => 'And out of all my sons — for the Lord has given me many sons — he has chosen my son Solomon to sit on the throne of the Lord\'s kingdom over Israel.',
                    6 => 'He said to me, \'Your son Solomon is the one who is to build my house and my courts, for I have chosen him to be my son, and I will be his father.',
                    7 => 'I will establish his kingdom forever if he perseveres in keeping my commands and my ordinances as he is doing today.\'',
                    8 => '"So now in the sight of all Israel, the assembly of the Lord, and in the hearing of our God, observe and follow all the commands of the Lord your God so that you may possess this good land and leave it as an inheritance to your descendants forever.',
                    9 => '"As for you, Solomon my son, know the God of your father, and serve him wholeheartedly and with a willing mind, for the Lord searches every heart and understands the intention of every thought. If you seek him, he will be found by you, but if you abandon him, he will reject you forever.',
                    10 => 'Realize now that the Lord has chosen you to build a house for the sanctuary. Be strong, and do it."',
                    11 => 'Then David gave his son Solomon the plans for the portico of the temple and its buildings, treasuries, upstairs rooms, inner rooms, and a room for the mercy seat.',
                    12 => 'The plans contained everything he had in mind for the courts of the Lord\'s house, all the surrounding chambers, the treasuries of God\'s house, and the treasuries for what is dedicated.',
                    13 => 'Also included were plans for the divisions of the priests and the Levites; all the work of service in the Lord\'s house; all the articles of service of the \'s house;',
                    14 => 'the weight of gold for all the articles for every kind of service; the weight of all the silver articles for every kind of service;',
                    15 => 'the weight of the gold lampstands and their gold lamps, including the weight of each lampstand and its lamps; the weight of each silver lampstand and its lamps, according to the service of each lampstand;',
                    16 => 'the weight of gold for each table for the rows of the Bread of the Presence and the silver for the silver tables;',
                    17 => 'the pure gold for the forks, sprinkling basins, and pitchers; the weight of each gold dish; the weight of each silver bowl;',
                    18 => 'the weight of refined gold for the altar of incense; and the plans for the chariot of the gold cherubim that spread out their wings and cover the ark of the Lord\'s covenant.',
                    19 => 'David concluded, "By the Lord\'s hand on me, he enabled me to understand everything in writing, all the details of the plan."',
                    20 => 'Then David said to his son Solomon, "Be strong and courageous, and do the work. Don\'t be afraid or discouraged, for the Lord God, my God, is with you. He won\'t leave you or abandon you until all the work for the service of the Lord\'s house is finished.',
                    21 => 'Here are the divisions of the priests and the Levites for all the service of God\'s house. Every willing person of any skill will be at your disposal for the work, and the leaders and all the people are at your every command."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                ],
            ],
            29 => [
                'sections' => [
                    1 => 'Contributions for Building the Temple',
                    2 => 'David\'s Prayer',
                    3 => 'The Enthronement of Solomon',
                    4 => 'A Summary of David\'s Life',
                ],
                'verses' => [
                    1 => 'Then King David said to all the assembly, "My son Solomon — God has chosen him alone — is young and inexperienced. The task is great because the building will not be built for a human but for the Lord God.',
                    2 => 'So to the best of my ability I\'ve made provision for the house of my God: gold for the gold articles, silver for the silver, bronze for the bronze, iron for the iron, and wood for the wood, as well as onyx, stones for mounting, antimony, stones of various colors, all kinds of precious stones, and a great quantity of marble.',
                    3 => 'Moreover, because of my delight in the house of my God, I now give my personal treasures of gold and silver for the house of my God over and above all that I\'ve provided for the holy house:',
                    4 => '100 tons of gold (gold of Ophir ) and 250 tons of refined silver for overlaying the walls of the buildings,',
                    5 => 'the gold for the gold work and the silver for the silver, for all the work to be done by the craftsmen. Now who will volunteer to consecrate himself to the Lord today? "',
                    6 => 'Then the leaders of the households, the leaders of the tribes of Israel, the commanders of thousands and of hundreds, and the officials in charge of the king\'s work gave willingly.',
                    7 => 'For the service of God\'s house they gave 185 tons of gold and 10,000 gold coins, 375 tons of silver, 675 tons of bronze, and 4,000 tons of iron.',
                    8 => 'Whoever had precious stones gave them to the treasury of the Lord\'s house under the care of Jehiel the Gershonite.',
                    9 => 'Then the people rejoiced because of their leaders\' willingness to give, for they had given to the wholeheartedly. King David also rejoiced greatly.',
                    10 => 'Then, for a second time, they made David\'s son Solomon king; they anointed him as the Lord\'s ruler, and Zadok as the priest.',
                    20 => 'Then David said to the whole assembly, "Blessed be the Lord your God." So the whole assembly praised the Lord God of their ancestors. They knelt low and paid homage to the Lord and the king.',
                    21 => 'The following day they offered sacrifices to the Lord and burnt offerings to the Lord: a thousand bulls, a thousand rams, and a thousand lambs, along with their drink offerings, and sacrifices in abundance for all Israel.',
                    23 => 'Solomon sat on the Lord\'s throne as king in place of his father David. He prospered, and all Israel obeyed him.',
                    24 => 'All the leaders and the mighty men, and all of King David\'s sons as well, pledged their allegiance to King Solomon.',
                    25 => 'The highly exalted Solomon in the sight of all Israel and bestowed on him such royal majesty as had not been bestowed on any king over Israel before him.',
                    26 => 'David son of Jesse was king over all Israel.',
                    27 => 'The length of his reign over Israel was forty years; he reigned in Hebron for seven years and in Jerusalem for thirty-three.',
                    28 => 'He died at a good old age, full of days, riches, and honor, and his son Solomon became king in his place.',
                    29 => 'As for the events of King David\'s reign, from beginning to end, note that they are written in the Events of the Seer Samuel, the Events of the Prophet Nathan, and the Events of the Seer Gad,',
                    30 => 'along with all his reign, his might, and the incidents that affected him and Israel and all the kingdoms of the surrounding lands.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 3,
                    20 => 2,
                    21 => 2,
                    23 => 3,
                    24 => 3,
                    25 => 3,
                    26 => 4,
                    27 => 4,
                    28 => 4,
                    29 => 4,
                    30 => 4,
                ],
            ],
        ];
    }
} 