<?php

declare(strict_types=1);

namespace BKuhl\BibleCSB\Book;

use BKuhl\BibleCSB\Book;
use BKuhl\BibleCSB\Testament;

class Hebrews extends Book
{
    private const ABBREVIATION = 'Heb';
    public const ID = 58;

    public function testament(): Testament
    {
        return Testament::NEW;
    }

    public function name(): string
    {
        return 'Hebrews';
    }

    public function position(): int
    {
        return self::ID;
    }

    public function abbreviation(): string
    {
        return self::ABBREVIATION;
    }

    /**
     * @return array<int, array{sections: array<int, string>, verses: array<int, string>, versesToSections: array<int, int>}>
     */
    protected function getChapterData(): array
    {
        return [
            1 => [
                'sections' => [
                    1 => 'The Nature of the Son',
                    2 => 'The Son Superior to Angels',
                ],
                'verses' => [
                    1 => 'Long ago God spoke to the ancestors by the prophets at different times and in different ways.',
                    2 => 'In these last days, he has spoken to us by his Son. God has appointed him heir of all things and made the universe through him.',
                    3 => 'The Son is the radiance of God\'s glory and the exact expression of his nature, sustaining all things by his powerful word. After making purification for sins, he sat down at the right hand of the Majesty on high.',
                    4 => 'So he became superior to the angels, just as the name he inherited is more excellent than theirs.',
                    5 => 'For to which of the angels did he ever say,',
                    6 => 'Again, when he brings his firstborn into the world, he says,',
                    7 => 'And about the angels he says:',
                    8 => 'but to the Son:',
                    10 => 'And:',
                    13 => 'Now to which of the angels has he ever said:',
                    14 => 'Are they not all ministering spirits sent out to serve those who are going to inherit salvation?',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 2,
                    6 => 2,
                    7 => 2,
                    8 => 2,
                    10 => 2,
                    13 => 2,
                    14 => 2,
                ],
            ],
            2 => [
                'sections' => [
                    1 => 'Warning against Neglect',
                    2 => 'Jesus and Humanity',
                ],
                'verses' => [
                    1 => 'For this reason, we must pay attention all the more to what we have heard, so that we will not drift away.',
                    2 => 'For if the message spoken through angels was legally binding and every transgression and disobedience received a just punishment,',
                    3 => 'how will we escape if we neglect such a great salvation? This salvation had its beginning when it was spoken of by the Lord, and it was confirmed to us by those who heard him.',
                    4 => 'At the same time, God also testified by signs and wonders, various miracles, and distributions of gifts from the Holy Spirit according to his will.',
                    5 => 'For he has not subjected to angels the world to come that we are talking about.',
                    6 => 'But someone somewhere has testified:',
                    8 => 'For in to him, he left nothing that is not subject to him. As it is, we do not yet see to him.',
                    9 => 'But we do see Jesus — so that by God\'s grace he might taste death for everyone — because he suffered death.',
                    10 => 'For in bringing many sons and daughters to glory, it was entirely appropriate that God — for whom and through whom all things exist — should make the pioneer of their salvation perfect through sufferings.',
                    11 => 'For the one who sanctifies and those who are sanctified all have one Father. That is why Jesus is not ashamed to call them brothers and sisters,',
                    12 => 'saying:',
                    13 => 'Again, And again,',
                    14 => 'Now since the children have flesh and blood in common, Jesus also shared in these, so that through his death he might destroy the one holding the power of death — that is, the devil —',
                    15 => 'and free those who were held in slavery all their lives by the fear of death.',
                    16 => 'For it is clear that he does not reach out to help angels, but to help Abraham\'s offspring.',
                    17 => 'Therefore, he had to be like his brothers and sisters in every way, so that he could become a merciful and faithful high priest in matters pertaining to God, to make atonement for the sins of the people.',
                    18 => 'For since he himself has suffered when he was tempted, he is able to help those who are tempted.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 2,
                    6 => 2,
                    8 => 2,
                    9 => 2,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                ],
            ],
            3 => [
                'sections' => [
                    1 => 'Our Apostle and High Priest',
                    2 => 'Warning against Unbelief',
                ],
                'verses' => [
                    1 => 'Therefore, holy brothers and sisters, who share in a heavenly calling, consider Jesus, the apostle and high priest of our confession.',
                    2 => 'He was faithful to the one who appointed him, just as Moses was in all God\'s household.',
                    3 => 'For Jesus is considered worthy of more glory than Moses, just as the builder has more honor than the house.',
                    4 => 'Now every house is built by someone, but the one who built everything is God.',
                    5 => 'Moses was faithful as a servant in all God\'s household, as a testimony to what would be said in the future.',
                    6 => 'But Christ was faithful as a Son over his household. And we are that household if we hold on to our confidence and the hope in which we boast.',
                    7 => 'Therefore, as the Holy Spirit says:',
                    12 => 'Watch out, brothers and sisters, so that there won\'t be in any of you an evil, unbelieving heart that turns away from the living God.',
                    13 => 'But encourage each other daily, while it is still called , so that none of you is hardened by sin\'s deception.',
                    14 => 'For we have become participants in Christ if we hold firmly until the end the reality that we had at the start.',
                    15 => 'As it is said:',
                    16 => 'For who heard and rebelled? Wasn\'t it all who came out of Egypt under Moses?',
                    17 => 'With whom was God angry for forty years? Wasn\'t it with those who sinned, whose bodies fell in the wilderness?',
                    18 => 'And to whom did he swear that they would not enter his rest, if not to those who disobeyed?',
                    19 => 'So we see that they were unable to enter because of unbelief.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                ],
            ],
            4 => [
                'sections' => [
                    1 => 'The Promised Rest',
                    2 => 'Our Great High Priest',
                ],
                'verses' => [
                    1 => 'Therefore, since the promise to enter his rest remains, let us beware that none of you be found to have fallen short.',
                    2 => 'For we also have received the good news just as they did. But the message they heard did not benefit them, since they were not united with those who heard it in faith.',
                    3 => 'even though his works have been finished since the foundation of the world.',
                    4 => 'For somewhere he has spoken about the seventh day in this way:',
                    5 => 'Again, in that passage he says,',
                    6 => 'Therefore, since it remains for some to enter it, and those who formerly received the good news did not enter because of disobedience,',
                    7 => 'he again specifies a certain day — . He specified this speaking through David after such a long time:',
                    8 => 'For if Joshua had given them rest, God would not have spoken later about another day.',
                    9 => 'Therefore, a Sabbath rest remains for God\'s people.',
                    10 => 'For the person who has entered his rest has rested from his own works, just as God did from his.',
                    11 => 'Let us, then, make every effort to enter that rest, so that no one will fall into the same pattern of disobedience.',
                    12 => 'For the word of God is living and effective and sharper than any double-edged sword, penetrating as far as the separation of soul and spirit, joints and marrow. It is able to judge the thoughts and intentions of the heart.',
                    13 => 'No creature is hidden from him, but all things are naked and exposed to the eyes of him to whom we must give an account.',
                    14 => 'Therefore, since we have a great high priest who has passed through the heavens — Jesus the Son of God — let us hold fast to our confession.',
                    15 => 'For we do not have a high priest who is unable to sympathize with our weaknesses, but one who has been tempted in every way as we are, yet without sin.',
                    16 => 'Therefore, let us approach the throne of grace with boldness, so that we may receive mercy and find grace to help us in time of need.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                ],
            ],
            5 => [
                'sections' => [
                    1 => 'Christ, a High Priest',
                    2 => 'The Problem of Immaturity',
                ],
                'verses' => [
                    1 => 'For every high priest taken from among men is appointed in matters pertaining to God for the people, to offer both gifts and sacrifices for sins.',
                    2 => 'He is able to deal gently with those who are ignorant and are going astray, since he is also clothed with weakness.',
                    3 => 'Because of this, he must make an offering for his own sins as well as for the people.',
                    4 => 'No one takes this honor on himself; instead, a person is called by God, just as Aaron was.',
                    5 => 'In the same way, Christ did not exalt himself to become a high priest, but God who said to him,',
                    6 => 'also says in another place,',
                    7 => 'During his earthly life, he offered prayers and appeals with loud cries and tears to the one who was able to save him from death, and he was heard because of his reverence.',
                    8 => 'Although he was the Son, he learned obedience from what he suffered.',
                    9 => 'After he was perfected, he became the source of eternal salvation for all who obey him,',
                    10 => 'and he was declared by God a high priest according to the order of Melchizedek.',
                    11 => 'We have a great deal to say about this, and it is difficult to explain, since you have become too lazy to understand.',
                    12 => 'Although by this time you ought to be teachers, you need someone to teach you the basic principles of God\'s revelation again. You need milk, not solid food.',
                    13 => 'Now everyone who lives on milk is inexperienced with the message about righteousness, because he is an infant.',
                    14 => 'But solid food is for the mature — for those whose senses have been trained to distinguish between good and evil.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                ],
            ],
            6 => [
                'sections' => [
                    1 => 'Warning against Falling Away',
                    2 => 'Inheriting the Promise',
                ],
                'verses' => [
                    1 => 'Therefore, let us leave the elementary teaching about Christ and go on to maturity, not laying again a foundation of repentance from dead works, faith in God,',
                    2 => 'teaching about ritual washings, laying on of hands, the resurrection of the dead, and eternal judgment.',
                    3 => 'And we will do this if God permits.',
                    4 => 'For it is impossible to renew to repentance those who were once enlightened, who tasted the heavenly gift, who shared in the Holy Spirit,',
                    5 => 'who tasted God\'s good word and the powers of the coming age,',
                    6 => 'and who have fallen away. This is because, to their own harm, they are recrucifying the Son of God and holding him up to contempt.',
                    7 => 'For the ground that drinks the rain that often falls on it and that produces vegetation useful to those for whom it is cultivated receives a blessing from God.',
                    8 => 'But if it produces thorns and thistles, it is worthless and about to be cursed, and at the end will be burned.',
                    9 => 'Even though we are speaking this way, dearly loved friends, in your case we are confident of things that are better and that pertain to salvation.',
                    10 => 'For God is not unjust; he will not forget your work and the love you demonstrated for his name by serving the saints — and by continuing to serve them.',
                    11 => 'Now we desire each of you to demonstrate the same diligence for the full assurance of your hope until the end,',
                    12 => 'so that you won\'t become lazy but will be imitators of those who inherit the promises through faith and perseverance.',
                    13 => 'For when God made a promise to Abraham, since he had no one greater to swear by, he swore by himself:',
                    14 => '',
                    15 => 'And so, after waiting patiently, Abraham obtained the promise.',
                    16 => 'For people swear by something greater than themselves, and for them a confirming oath ends every dispute.',
                    17 => 'Because God wanted to show his unchangeable purpose even more clearly to the heirs of the promise, he guaranteed it with an oath,',
                    18 => 'so that through two unchangeable things, in which it is impossible for God to lie, we who have fled for refuge might have strong encouragement to seize the hope set before us.',
                    19 => 'We have this hope as an anchor for the soul, firm and secure. It enters the inner sanctuary behind the curtain.',
                    20 => 'Jesus has entered there on our behalf as a forerunner, because he has become a high priest forever according to the order of Melchizedek.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                    20 => 2,
                ],
            ],
            7 => [
                'sections' => [
                    1 => 'The Greatness of Melchizedek',
                    2 => 'A Superior Priesthood',
                ],
                'verses' => [
                    1 => 'For this Melchizedek, king of Salem, priest of God Most High, met Abraham and blessed him as he returned from defeating the kings,',
                    2 => 'and Abraham gave him a tenth of everything. First, his name means king of righteousness, then also, king of Salem, meaning king of peace.',
                    3 => 'Without father, mother, or genealogy, having neither beginning of days nor end of life, but resembling the Son of God, he remains a priest forever.',
                    4 => 'Now consider how great this man was: even Abraham the patriarch gave a tenth of the plunder to him.',
                    5 => 'The sons of Levi who receive the priestly office have a command according to the law to collect a tenth from the people — that is, from their brothers and sisters — though they have also descended from Abraham.',
                    6 => 'But one without this lineage collected a tenth from Abraham and blessed the one who had the promises.',
                    7 => 'Without a doubt, the inferior is blessed by the superior.',
                    8 => 'In the one case, men who will die receive a tenth, but in the other case, Scripture testifies that he lives.',
                    9 => 'And in a sense Levi himself, who receives a tenth, has paid a tenth through Abraham,',
                    10 => 'for he was still within his ancestor when Melchizedek met him.',
                    11 => 'Now if perfection came through the Levitical priesthood (for on the basis of it the people received the law ), what further need was there for another priest to appear, said to be according to the order of Melchizedek and not according to the order of Aaron?',
                    12 => 'For when there is a change of the priesthood, there must be a change of law as well.',
                    13 => 'For the one these things are spoken about belonged to a different tribe. No one from it has served at the altar.',
                    14 => 'Now it is evident that our Lord came from Judah, and Moses said nothing about that tribe concerning priests.',
                    15 => 'And this becomes clearer if another priest like Melchizedek appears,',
                    16 => 'who did not become a priest based on a legal regulation about physical descent but based on the power of an indestructible life.',
                    17 => 'For it has been testified:',
                    18 => 'So the previous command is annulled because it was weak and unprofitable',
                    19 => '(for the law perfected nothing), but a better hope is introduced, through which we draw near to God.',
                    20 => 'None of this happened without an oath. For others became priests without an oath,',
                    21 => 'but he became a priest with an oath made by the one who said to him:',
                    22 => 'Because of this oath, Jesus has also become the guarantee of a better covenant.',
                    23 => 'Now many have become Levitical priests, since they are prevented by death from remaining in office.',
                    24 => 'But because he remains forever, he holds his priesthood permanently.',
                    25 => 'Therefore, he is able to save completely those who come to God through him, since he always lives to intercede for them.',
                    26 => 'For this is the kind of high priest we need: holy, innocent, undefiled, separated from sinners, and exalted above the heavens.',
                    27 => 'He doesn\'t need to offer sacrifices every day, as high priests do — first for their own sins, then for those of the people. He did this once for all time when he offered himself.',
                    28 => 'For the law appoints as high priests men who are weak, but the promise of the oath, which came after the law, appoints a Son, who has been perfected forever.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 2,
                    24 => 2,
                    25 => 2,
                    26 => 2,
                    27 => 2,
                    28 => 2,
                ],
            ],
            8 => [
                'sections' => [
                    1 => 'A Heavenly Priesthood',
                    2 => 'A Superior Covenant',
                ],
                'verses' => [
                    1 => 'Now the main point of what is being said is this: We have this kind of high priest, who sat down at the right hand of the throne of the Majesty in the heavens,',
                    2 => 'a minister of the sanctuary and the true tabernacle that was set up by the Lord and not man.',
                    3 => 'For every high priest is appointed to offer gifts and sacrifices; therefore, it was necessary for this priest also to have something to offer.',
                    4 => 'Now if he were on earth, he wouldn\'t be a priest, since there are those offering the gifts prescribed by the law.',
                    5 => 'These serve as a copy and shadow of the heavenly things, as Moses was warned when he was about to complete the tabernacle. For God said,',
                    6 => 'But Jesus has now obtained a superior ministry, and to that degree he is the mediator of a better covenant, which has been established on better promises.',
                    7 => 'For if that first covenant had been faultless, there would have been no occasion for a second one.',
                    8 => 'But finding fault with his people, he says:',
                    13 => 'By saying , he has declared that the first is obsolete. And what is obsolete and growing old is about to pass away.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 2,
                    8 => 2,
                    13 => 2,
                ],
            ],
            9 => [
                'sections' => [
                    1 => 'Old Covenant Ministry',
                    2 => 'New Covenant Ministry',
                ],
                'verses' => [
                    1 => 'Now the first covenant also had regulations for ministry and an earthly sanctuary.',
                    2 => 'For a tabernacle was set up, and in the first room, which is called the holy place, were the lampstand, the table, and the presentation loaves.',
                    3 => 'Behind the second curtain was a tent called the most holy place.',
                    4 => 'It had the gold altar of incense and the ark of the covenant, covered with gold on all sides, in which was a gold jar containing the manna, Aaron\'s staff that budded, and the tablets of the covenant.',
                    5 => 'The cherubim of glory were above the ark overshadowing the mercy seat. It is not possible to speak about these things in detail right now.',
                    6 => 'With these things prepared like this, the priests enter the first room repeatedly, performing their ministry.',
                    7 => 'But the high priest alone enters the second room, and he does that only once a year, and never without blood, which he offers for himself and for the sins the people had committed in ignorance.',
                    8 => 'The Holy Spirit was making it clear that the way into the most holy place had not yet been disclosed while the first tabernacle was still standing.',
                    9 => 'This is a symbol for the present time, during which gifts and sacrifices are offered that cannot perfect the worshiper\'s conscience.',
                    10 => 'They are physical regulations and only deal with food, drink, and various washings imposed until the time of the new order.',
                    11 => 'But Christ has appeared as a high priest of the good things that have come. In the greater and more perfect tabernacle not made with hands (that is, not of this creation ),',
                    12 => 'he entered the most holy place once for all time, not by the blood of goats and calves, but by his own blood, having obtained eternal redemption.',
                    13 => 'For if the blood of goats and bulls and the ashes of a young cow, sprinkling those who are defiled, sanctify for the purification of the flesh,',
                    14 => 'how much more will the blood of Christ, who through the eternal Spirit offered himself without blemish to God, cleanse our consciences from dead works so that we can serve the living God?',
                    15 => 'Therefore, he is the mediator of a new covenant, so that those who are called might receive the promise of the eternal inheritance, because a death has taken place for redemption from the transgressions committed under the first covenant.',
                    16 => 'Where a will exists, the death of the one who made it must be established.',
                    17 => 'For a will is valid only when people die, since it is never in effect while the one who made it is living.',
                    18 => 'That is why even the first covenant was inaugurated with blood.',
                    19 => 'For when every command had been proclaimed by Moses to all the people according to the law, he took the blood of calves and goats, along with water, scarlet wool, and hyssop, and sprinkled the scroll itself and all the people,',
                    20 => 'saying,',
                    21 => 'In the same way, he sprinkled the tabernacle and all the articles of worship with blood.',
                    22 => 'According to the law almost everything is purified with blood, and without the shedding of blood there is no forgiveness.',
                    23 => 'Therefore, it was necessary for the copies of the things in the heavens to be purified with these sacrifices, but the heavenly things themselves to be purified with better sacrifices than these.',
                    24 => 'For Christ did not enter a sanctuary made with hands (only a model of the true one) but into heaven itself, so that he might now appear in the presence of God for us.',
                    25 => 'He did not do this to offer himself many times, as the high priest enters the sanctuary yearly with the blood of another.',
                    26 => 'Otherwise, he would have had to suffer many times since the foundation of the world. But now he has appeared one time, at the end of the ages, for the removal of sin by the sacrifice of himself.',
                    27 => 'And just as it is appointed for people to die once — and after this, judgment —',
                    28 => 'so also Christ, having been offered once to bear the sins of many, will appear a second time, not to bear sin, but to bring salvation to those who are waiting for him.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 2,
                    24 => 2,
                    25 => 2,
                    26 => 2,
                    27 => 2,
                    28 => 2,
                ],
            ],
            10 => [
                'sections' => [
                    1 => 'The Perfect Sacrifice',
                    2 => 'Exhortations to Godliness',
                    3 => 'Warning against Deliberate Sin',
                ],
                'verses' => [
                    1 => 'Since the law has only a shadow of the good things to come, and not the reality itself of those things, it can never perfect the worshipers by the same sacrifices they continually offer year after year.',
                    2 => 'Otherwise, wouldn\'t they have stopped being offered, since the worshipers, purified once and for all, would no longer have any consciousness of sins?',
                    3 => 'But in the sacrifices there is a reminder of sins year after year.',
                    4 => 'For it is impossible for the blood of bulls and goats to take away sins.',
                    5 => 'Therefore, as he was coming into the world, he said:',
                    8 => 'After he says above, (which are offered according to the law ),',
                    9 => 'he then says, He takes away the first to establish the second.',
                    10 => 'By this will, we have been sanctified through the offering of the body of Jesus Christ once for all time.',
                    11 => 'Every priest stands day after day ministering and offering the same sacrifices time after time, which can never take away sins.',
                    12 => 'But this man, after offering one sacrifice for sins forever, sat down at the right hand of God.',
                    13 => 'He is now waiting until his enemies are made his footstool.',
                    14 => 'For by one offering he has perfected forever those who are sanctified.',
                    15 => 'The Holy Spirit also testifies to us about this. For after he says:',
                    16 => '',
                    18 => 'Now where there is forgiveness of these, there is no longer an offering for sin.',
                    19 => 'Therefore, brothers and sisters, since we have boldness to enter the sanctuary through the blood of Jesus —',
                    20 => 'he has inaugurated for us a new and living way through the curtain (that is, through his flesh ) —',
                    21 => 'and since we have a great high priest over the house of God,',
                    22 => 'let us draw near with a true heart in full assurance of faith, with our hearts sprinkled clean from an evil conscience and our bodies washed in pure water.',
                    23 => 'Let us hold on to the confession of our hope without wavering, since he who promised is faithful.',
                    24 => 'And let us consider one another in order to provoke love and good works,',
                    25 => 'not neglecting to gather together, as some are in the habit of doing, but encouraging each other, and all the more as you see the day approaching.',
                    26 => 'For if we deliberately go on sinning after receiving the knowledge of the truth, there no longer remains a sacrifice for sins,',
                    27 => 'but a terrifying expectation of judgment and the fury of a fire about to consume the adversaries.',
                    28 => 'Anyone who disregarded the law of Moses died without mercy, based on the testimony of two or three witnesses.',
                    29 => 'How much worse punishment do you think one will deserve who has trampled on the Son of God, who has regarded as profane the blood of the covenant by which he was sanctified, and who has insulted the Spirit of grace?',
                    30 => 'For we know the one who has said,',
                    31 => 'It is a terrifying thing to fall into the hands of the living God.',
                    32 => 'Remember the earlier days when, after you had been enlightened, you endured a hard struggle with sufferings.',
                    33 => 'Sometimes you were publicly exposed to taunts and afflictions, and at other times you were companions of those who were treated that way.',
                    34 => 'For you sympathized with the prisoners and accepted with joy the confiscation of your possessions, because you know that you yourselves have a better and enduring possession.',
                    35 => 'So don\'t throw away your confidence, which has a great reward.',
                    36 => 'For you need endurance, so that after you have done God\'s will, you may receive what was promised.',
                    39 => 'But we are not those who draw back and are destroyed, but those who have faith and are saved.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    18 => 1,
                    19 => 2,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 2,
                    24 => 2,
                    25 => 2,
                    26 => 3,
                    27 => 3,
                    28 => 3,
                    29 => 3,
                    30 => 3,
                    31 => 3,
                    32 => 3,
                    33 => 3,
                    34 => 3,
                    35 => 3,
                    36 => 3,
                    39 => 3,
                ],
            ],
            11 => [
                'sections' => [
                    1 => 'Living by Faith',
                ],
                'verses' => [
                    1 => 'Now faith is the reality of what is hoped for, the proof of what is not seen.',
                    2 => 'For by this our ancestors were approved.',
                    3 => 'By faith we understand that the universe was created by the word of God, so that what is seen was made from things that are not visible.',
                    4 => 'By faith Abel offered to God a better sacrifice than Cain did. By faith he was approved as a righteous man, because God approved his gifts, and even though he is dead, he still speaks through his faith.',
                    5 => 'By faith Enoch was taken away, and so he did not experience death. For before he was taken away, he was approved as one who pleased God.',
                    6 => 'Now without faith it is impossible to please God, since the one who draws near to him must believe that he exists and that he rewards those who seek him.',
                    7 => 'By faith Noah, after he was warned about what was not yet seen and motivated by godly fear, built an ark to deliver his family. By faith he condemned the world and became an heir of the righteousness that comes by faith.',
                    8 => 'By faith Abraham, when he was called, obeyed and set out for a place that he was going to receive as an inheritance. He went out, even though he did not know where he was going.',
                    9 => 'By faith he stayed as a foreigner in the land of promise, living in tents as did Isaac and Jacob, coheirs of the same promise.',
                    10 => 'For he was looking forward to the city that has foundations, whose architect and builder is God.',
                    11 => 'By faith even Sarah herself, when she was unable to have children, received power to conceive offspring, even though she was past the age, since she considered that the one who had promised was faithful.',
                    12 => 'Therefore, from one man — in fact, from one as good as dead — came offspring as numerous as the stars of the sky and as innumerable as the grains of sand along the seashore.',
                    13 => 'These all died in faith, although they had not received the things that were promised. But they saw them from a distance, greeted them, and confessed that they were foreigners and temporary residents on the earth.',
                    14 => 'Now those who say such things make it clear that they are seeking a homeland.',
                    15 => 'If they were thinking about where they came from, they would have had an opportunity to return.',
                    16 => 'But they now desire a better place — a heavenly one. Therefore, God is not ashamed to be called their God, for he has prepared a city for them.',
                    17 => 'By faith Abraham, when he was tested, offered up Isaac. He received the promises and yet he was offering his one and only son,',
                    18 => 'the one to whom it had been said,',
                    19 => 'He considered God to be able even to raise someone from the dead; therefore, he received him back, figuratively speaking.',
                    20 => 'By faith Isaac blessed Jacob and Esau concerning things to come.',
                    21 => 'By faith Jacob, when he was dying, blessed each of the sons of Joseph, and',
                    22 => 'By faith Joseph, as he was nearing the end of his life, mentioned the exodus of the Israelites and gave instructions concerning his bones.',
                    23 => 'By faith Moses, after he was born, was hidden by his parents for three months, because they saw that the child was beautiful, and they didn\'t fear the king\'s edict.',
                    24 => 'By faith Moses, when he had grown up, refused to be called the son of Pharaoh\'s daughter',
                    25 => 'and chose to suffer with the people of God rather than to enjoy the fleeting pleasure of sin.',
                    26 => 'For he considered reproach for the sake of Christ to be greater wealth than the treasures of Egypt, since he was looking ahead to the reward.',
                    27 => 'By faith he left Egypt behind, not being afraid of the king\'s anger, for Moses persevered as one who sees him who is invisible.',
                    28 => 'By faith he instituted the Passover and the sprinkling of the blood, so that the destroyer of the firstborn might not touch the Israelites.',
                    29 => 'By faith they crossed the Red Sea as though they were on dry land. When the Egyptians attempted to do this, they were drowned.',
                    30 => 'By faith the walls of Jericho fell down after being marched around by the Israelites for seven days.',
                    31 => 'By faith Rahab the prostitute welcomed the spies in peace and didn\'t perish with those who disobeyed.',
                    32 => 'And what more can I say? Time is too short for me to tell about Gideon, Barak, Samson, Jephthah, David, Samuel, and the prophets,',
                    33 => 'who by faith conquered kingdoms, administered justice, obtained promises, shut the mouths of lions,',
                    34 => 'quenched the raging of fire, escaped the edge of the sword, gained strength in weakness, became mighty in battle, and put foreign armies to flight.',
                    35 => 'Women received their dead, raised to life again. Other people were tortured, not accepting release, so that they might gain a better resurrection.',
                    36 => 'Others experienced mockings and scourgings, as well as bonds and imprisonment.',
                    37 => 'They were stoned, they were sawed in two, they died by the sword, they wandered about in sheepskins, in goatskins, destitute, afflicted, and mistreated.',
                    38 => 'The world was not worthy of them. They wandered in deserts and on mountains, hiding in caves and holes in the ground.',
                    39 => 'All these were approved through their faith, but they did not receive what was promised,',
                    40 => 'since God had provided something better for us, so that they would not be made perfect without us.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 1,
                    23 => 1,
                    24 => 1,
                    25 => 1,
                    26 => 1,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                    30 => 1,
                    31 => 1,
                    32 => 1,
                    33 => 1,
                    34 => 1,
                    35 => 1,
                    36 => 1,
                    37 => 1,
                    38 => 1,
                    39 => 1,
                    40 => 1,
                ],
            ],
            12 => [
                'sections' => [
                    1 => 'The Call to Endurance',
                    2 => 'Fatherly Discipline',
                    3 => 'Warning against Rejecting God\'s Grace',
                ],
                'verses' => [
                    1 => 'Therefore, since we also have such a large cloud of witnesses surrounding us, let us lay aside every hindrance and the sin that so easily ensnares us. Let us run with endurance the race that lies before us,',
                    2 => 'keeping our eyes on Jesus, the pioneer and perfecter of our faith. For the joy that lay before him, he endured the cross, despising the shame, and sat down at the right hand of the throne of God.',
                    3 => 'For consider him who endured such hostility from sinners against himself, so that you won\'t grow weary and give up.',
                    4 => 'In struggling against sin, you have not yet resisted to the point of shedding your blood.',
                    5 => 'And you have forgotten the exhortation that addresses you as sons:',
                    7 => 'Endure suffering as discipline: God is dealing with you as sons. For what son is there that a father does not discipline?',
                    8 => 'But if you are without discipline — which all receive — then you are illegitimate children and not sons.',
                    9 => 'Furthermore, we had human fathers discipline us, and we respected them. Shouldn\'t we submit even more to the Father of spirits and live?',
                    10 => 'For they disciplined us for a short time based on what seemed good to them, but he does it for our benefit, so that we can share his holiness.',
                    11 => 'No discipline seems enjoyable at the time, but painful. Later on, however, it yields the peaceful fruit of righteousness to those who have been trained by it.',
                    12 => 'Therefore, strengthen your tired hands and weakened knees,',
                    13 => 'and make straight paths for your feet, so that what is lame may not be dislocated but healed instead.',
                    14 => 'Pursue peace with everyone, and holiness — without it no one will see the Lord.',
                    15 => 'Make sure that no one falls short of the grace of God and that no root of bitterness springs up, causing trouble and defiling many.',
                    16 => 'And make sure that there isn\'t any immoral or irreverent person like Esau, who sold his birthright in exchange for a single meal.',
                    17 => 'For you know that later, when he wanted to inherit the blessing, he was rejected, even though he sought it with tears, because he didn\'t find any opportunity for repentance.',
                    18 => 'For you have not come to what could be touched, to a blazing fire, to darkness, gloom, and storm,',
                    19 => 'to the blast of a trumpet, and the sound of words. Those who heard it begged that not another word be spoken to them,',
                    20 => 'for they could not bear what was commanded:',
                    21 => 'The appearance was so terrifying that Moses said,',
                    22 => 'Instead, you have come to Mount Zion, to the city of the living God (the heavenly Jerusalem), to myriads of angels, a festive gathering,',
                    23 => 'to the assembly of the firstborn whose names have been written in heaven, to a Judge, who is God of all, to the spirits of righteous people made perfect,',
                    24 => 'and to Jesus, the mediator of a new covenant, and to the sprinkled blood, which says better things than the blood of Abel.',
                    25 => 'See to it that you do not reject the one who speaks. For if they did not escape when they rejected him who warned them on earth, even less will we if we turn away from him who warns us from heaven.',
                    26 => 'His voice shook the earth at that time, but now he has promised,',
                    27 => 'This expression, "Yet once more," indicates the removal of what can be shaken — that is, created things — so that what is not shaken might remain.',
                    28 => 'Therefore, since we are receiving a kingdom that cannot be shaken, let us be thankful. By it, we may serve God acceptably, with reverence and awe,',
                    29 => 'for our God is a consuming fire.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 2,
                    4 => 2,
                    5 => 2,
                    7 => 2,
                    8 => 2,
                    9 => 2,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 3,
                    15 => 3,
                    16 => 3,
                    17 => 3,
                    18 => 3,
                    19 => 3,
                    20 => 3,
                    21 => 3,
                    22 => 3,
                    23 => 3,
                    24 => 3,
                    25 => 3,
                    26 => 3,
                    27 => 3,
                    28 => 3,
                    29 => 3,
                ],
            ],
            13 => [
                'sections' => [
                    1 => 'Final Exhortations',
                    2 => 'Benediction and Farewell',
                ],
                'verses' => [
                    1 => 'Let brotherly love continue.',
                    2 => 'Don\'t neglect to show hospitality, for by doing this some have welcomed angels as guests without knowing it.',
                    3 => 'Remember those in prison, as though you were in prison with them, and the mistreated, as though you yourselves were suffering bodily.',
                    4 => 'Marriage is to be honored by all and the marriage bed kept undefiled, because God will judge the sexually immoral and adulterers.',
                    5 => 'Keep your life free from the love of money. Be satisfied with what you have, for he himself has said,',
                    6 => 'Therefore, we may boldly say,',
                    7 => 'Remember your leaders who have spoken God\'s word to you. As you carefully observe the outcome of their lives, imitate their faith.',
                    8 => 'Jesus Christ is the same yesterday, today, and forever.',
                    9 => 'Don\'t be led astray by various kinds of strange teachings; for it is good for the heart to be established by grace and not by food regulations, since those who observe them have not benefited.',
                    10 => 'We have an altar from which those who worship at the tabernacle do not have a right to eat.',
                    11 => 'For the bodies of those animals whose blood is brought into the most holy place by the high priest as a sin offering are burned outside the camp.',
                    12 => 'Therefore, Jesus also suffered outside the gate, so that he might sanctify the people by his own blood.',
                    13 => 'Let us, then, go to him outside the camp, bearing his disgrace.',
                    14 => 'For we do not have an enduring city here; instead, we seek the one to come.',
                    15 => 'Therefore, through him let us continually offer up to God a sacrifice of praise, that is, the fruit of lips that confess his name.',
                    16 => 'Don\'t neglect to do what is good and to share, for God is pleased with such sacrifices.',
                    17 => 'Obey your leaders and submit to them, since they keep watch over your souls as those who will give an account, so that they can do this with joy and not with grief, for that would be unprofitable for you.',
                    18 => 'Pray for us, for we are convinced that we have a clear conscience, wanting to conduct ourselves honorably in everything.',
                    19 => 'And I urge you all the more to pray that I may be restored to you very soon.',
                    20 => 'Now may the God of peace, who brought up from the dead our Lord Jesus — the great Shepherd of the sheep — through the blood of the everlasting covenant,',
                    21 => 'equip you with everything good to do his will, working in us what is pleasing in his sight, through Jesus Christ, to whom be glory forever and ever. Amen.',
                    22 => 'Brothers and sisters, I urge you to receive this message of exhortation, for I have written to you briefly.',
                    23 => 'Be aware that our brother Timothy has been released. If he comes soon enough, he will be with me when I see you.',
                    24 => 'Greet all your leaders and all the saints. Those who are from Italy send you greetings.',
                    25 => 'Grace be with you all.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 2,
                    24 => 2,
                    25 => 2,
                ],
            ],
        ];
    }
} 