<?php

declare(strict_types=1);

namespace BKuhl\BibleCSB\Book;

use BKuhl\BibleCSB\Book;
use BKuhl\BibleCSB\Testament;

class Nehemiah extends Book
{
    public const ABBREVIATION = 'Neh';
    public const ID = 16;

    public function testament(): Testament
    {
        return Testament::OLD;
    }

    public function name(): string
    {
        return 'Nehemiah';
    }

    public function position(): int
    {
        return self::ID;
    }

    public function abbreviation(): string
    {
        return self::ABBREVIATION;
    }

    /**
     * @return array<int, array{sections: array<int, string>, verses: array<int, string>, versesToSections: array<int, int>}>
     */
    protected function getChapterData(): array
    {
        return [
            1 => [
                'sections' => [
                    1 => 'News from Jerusalem',
                    2 => 'Nehemiah\'s Prayer',
                ],
                'verses' => [
                    1 => 'During the month of Chislev in the twentieth year, when I was in the fortress city of Susa,',
                    2 => 'Hanani, one of my brothers, arrived with men from Judah, and I questioned them about Jerusalem and the Jewish remnant that had survived the exile.',
                    3 => 'They said to me, "The remnant in the province, who survived the exile, are in great trouble and disgrace. Jerusalem\'s wall has been broken down, and its gates have been burned."',
                    4 => 'When I heard these words, I sat down and wept. I mourned for a number of days, fasting and praying before the God of the heavens.',
                    5 => 'I said,',
                    11 => 'At the time, I was the king\'s cupbearer.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 2,
                    5 => 2,
                    11 => 2,
                ],
            ],
            2 => [
                'sections' => [
                    1 => 'Nehemiah Sent to Jerusalem',
                    2 => 'Preparing to Rebuild the Walls',
                ],
                'verses' => [
                    1 => 'During the month of Nisan in the twentieth year of King Artaxerxes, when wine was set before him, I took the wine and gave it to the king. I had never been sad in his presence,',
                    2 => 'I was overwhelmed with fear',
                    3 => 'and replied to the king, "May the king live forever! Why should I not be sad when the city where my ancestors are buried lies in ruins and its gates have been destroyed by fire? "',
                    4 => 'So I prayed to the God of the heavens',
                    5 => 'and answered the king, "If it pleases the king, and if your servant has found favor with you, send me to Judah and to the city where my ancestors are buried, so that I may rebuild it."',
                    6 => 'The king, with the queen seated beside him, asked me, "How long will your journey take, and when will you return? " So I gave him a definite time, and it pleased the king to send me.',
                    7 => 'I also said to the king, "If it pleases the king, let me have letters written to the governors of the region west of the Euphrates River, so that they will grant me safe passage until I reach Judah.',
                    8 => 'And let me have a letter written to Asaph, keeper of the king\'s forest, so that he will give me timber to rebuild the gates of the temple\'s fortress, the city wall, and the home where I will live." The king granted my requests, for the gracious hand of my God was on me.',
                    9 => 'I went to the governors of the region west of the Euphrates and gave them the king\'s letters. The king had also sent officers of the infantry and cavalry with me.',
                    10 => 'When Sanballat the Horonite and Tobiah the Ammonite official heard that someone had come to pursue the prosperity of the Israelites, they were greatly displeased.',
                    11 => 'After I arrived in Jerusalem and had been there three days,',
                    12 => 'I got up at night and took a few men with me. I didn\'t tell anyone what my God had laid on my heart to do for Jerusalem. The only animal I took was the one I was riding.',
                    13 => 'I went out at night through the Valley Gate toward the Serpent\'s Well and the Dung Gate, and I inspected the walls of Jerusalem that had been broken down and its gates that had been destroyed by fire.',
                    14 => 'I went on to the Fountain Gate and the King\'s Pool, but farther down it became too narrow for my animal to go through.',
                    15 => 'So I went up at night by way of the valley and inspected the wall. Then heading back, I entered through the Valley Gate and returned.',
                    16 => 'The officials did not know where I had gone or what I was doing, for I had not yet told the Jews, priests, nobles, officials, or the rest of those who would be doing the work.',
                    17 => 'So I said to them, "You see the trouble we are in. Jerusalem lies in ruins and its gates have been burned. Come, let\'s rebuild Jerusalem\'s wall, so that we will no longer be a disgrace."',
                    18 => 'I told them how the gracious hand of my God had been on me, and what the king had said to me. They said, "Let\'s start rebuilding," and their hands were strengthened to do this good work.',
                    19 => 'When Sanballat the Horonite, Tobiah the Ammonite official, and Geshem the Arab heard about this, they mocked and despised us, and said, "What is this you\'re doing? Are you rebelling against the king? "',
                    20 => 'I gave them this reply, "The God of the heavens is the one who will grant us success. We, his servants, will start building, but you have no share, right, or historic claim in Jerusalem."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                    20 => 2,
                ],
            ],
            3 => [
                'sections' => [
                    1 => 'Rebuilding the Walls',
                    2 => 'Fish Gate',
                    3 => 'Old Gate, Broad Wall, and Tower of the Ovens',
                    4 => 'Valley Gate, Dung Gate, and Fountain Gate',
                    5 => 'The Angle, Water Gate, and Tower on Ophel',
                    6 => 'Horse Gate, Inspection Gate, and Sheep Gate',
                ],
                'verses' => [
                    1 => 'The high priest Eliashib and his fellow priests began rebuilding the Sheep Gate. They dedicated it and installed its doors. After building the wall to the Tower of the Hundred and the Tower of Hananel, they dedicated it.',
                    2 => 'The men of Jericho built next to Eliashib, and next to them Zaccur son of Imri built.',
                    3 => 'The sons of Hassenaah built the Fish Gate. They built it with beams and installed its doors, bolts, and bars.',
                    4 => 'Next to them Meremoth son of Uriah, son of Hakkoz, made repairs. Beside them Meshullam son of Berechiah, son of Meshezabel, made repairs. Next to them Zadok son of Baana made repairs.',
                    5 => 'Beside them the Tekoites made repairs, but their nobles did not lift a finger to help their supervisors.',
                    6 => 'Joiada son of Paseah and Meshullam son of Besodeiah repaired the Old Gate. They built it with beams and installed its doors, bolts, and bars.',
                    7 => 'Next to them the repairs were done by Melatiah the Gibeonite, Jadon the Meronothite, and the men of Gibeon and Mizpah, who were under the authority of the governor of the region west of the Euphrates River.',
                    8 => 'After him Uzziel son of Harhaiah, the goldsmith, made repairs, and next to him Hananiah son of the perfumer made repairs. They restored Jerusalem as far as the Broad Wall.',
                    9 => 'Next to them Rephaiah son of Hur, ruler of half the district of Jerusalem, made repairs.',
                    10 => 'After them Jedaiah son of Harumaph made repairs across from his house. Next to him Hattush the son of Hashabneiah made repairs.',
                    11 => 'Malchijah son of Harim and Hasshub son of Pahath-moab made repairs to another section, as well as to the Tower of the Ovens.',
                    12 => 'Beside him Shallum son of Hallohesh, ruler of half the district of Jerusalem, made repairs — he and his daughters.',
                    13 => 'Hanun and the inhabitants of Zanoah repaired the Valley Gate. They rebuilt it and installed its doors, bolts, and bars, and repaired five hundred yards of the wall to the Dung Gate.',
                    14 => 'Malchijah son of Rechab, ruler of the district of Beth-haccherem, repaired the Dung Gate. He rebuilt it and installed its doors, bolts, and bars.',
                    15 => 'Shallun son of Col-hozeh, ruler of the district of Mizpah, repaired the Fountain Gate. He rebuilt it and roofed it. Then he installed its doors, bolts, and bars. He also made repairs to the wall of the Pool of Shelah near the king\'s garden, as far as the stairs that descend from the city of David.',
                    16 => 'After him Nehemiah son of Azbuk, ruler of half the district of Beth-zur, made repairs up to a point opposite the tombs of David, as far as the artificial pool and the House of the Warriors.',
                    17 => 'Next to him the Levites made repairs under Rehum son of Bani. Beside him Hashabiah, ruler of half the district of Keilah, made repairs for his district.',
                    18 => 'After him their fellow Levites made repairs under Binnui son of Henadad, ruler of half the district of Keilah.',
                    19 => 'Next to him Ezer son of Jeshua, ruler of Mizpah, made repairs to another section opposite the ascent to the armory at the Angle.',
                    20 => 'After him Baruch son of Zabbai diligently repaired another section, from the Angle to the door of the house of the high priest Eliashib.',
                    21 => 'Beside him Meremoth son of Uriah, son of Hakkoz, made repairs to another section, from the door of Eliashib\'s house to the end of his house.',
                    22 => 'And next to him the priests from the surrounding area made repairs.',
                    23 => 'After them Benjamin and Hasshub made repairs opposite their house. Beside them Azariah son of Maaseiah, son of Ananiah, made repairs beside his house.',
                    24 => 'After him Binnui son of Henadad made repairs to another section, from the house of Azariah to the Angle and the corner.',
                    25 => 'Palal son of Uzai made repairs opposite the Angle and tower that juts out from the king\'s upper palace, by the courtyard of the guard. Beside him Pedaiah son of Parosh',
                    26 => 'and the temple servants living on Ophel made repairs opposite the Water Gate toward the east and the tower that juts out.',
                    27 => 'Next to him the Tekoites made repairs to another section from a point opposite the great tower that juts out, as far as the wall of Ophel.',
                    28 => 'Each of the priests made repairs above the Horse Gate, each opposite his own house.',
                    29 => 'After them Zadok son of Immer made repairs opposite his house. And beside him Shemaiah son of Shecaniah, guard of the East Gate, made repairs.',
                    30 => 'After them Meshullam son of Berechiah made repairs opposite his room.',
                    31 => 'Next to him Malchijah, one of the goldsmiths, made repairs to the house of the temple servants and the merchants, opposite the Inspection Gate, and as far as the upstairs room on the corner.',
                    32 => 'The goldsmiths and merchants made repairs between the upstairs room on the corner and the Sheep Gate.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 2,
                    4 => 2,
                    5 => 2,
                    6 => 3,
                    7 => 3,
                    8 => 3,
                    9 => 3,
                    10 => 3,
                    11 => 3,
                    12 => 3,
                    13 => 4,
                    14 => 4,
                    15 => 4,
                    16 => 4,
                    17 => 4,
                    18 => 4,
                    19 => 4,
                    20 => 5,
                    21 => 5,
                    22 => 5,
                    23 => 5,
                    24 => 5,
                    25 => 5,
                    26 => 5,
                    27 => 5,
                    28 => 6,
                    29 => 6,
                    30 => 6,
                    31 => 6,
                    32 => 6,
                ],
            ],
            4 => [
                'sections' => [
                    1 => 'Progress in Spite of Opposition',
                    2 => 'Sword and Trowel',
                ],
                'verses' => [
                    1 => 'When Sanballat heard that we were rebuilding the wall, he became furious. He mocked the Jews',
                    2 => 'before his colleagues and the powerful men of Samaria and said, "What are these pathetic Jews doing? Can they restore it by themselves? Will they offer sacrifices? Will they ever finish it? Can they bring these burnt stones back to life from the mounds of rubble? "',
                    3 => 'Then Tobiah the Ammonite, who was beside him, said, "Indeed, even if a fox climbed up what they are building, he would break down their stone wall! "',
                    4 => 'Listen, our God, for we are despised. Make their insults return on their own heads and let them be taken as plunder to a land of captivity.',
                    5 => 'Do not cover their guilt or let their sin be erased from your sight, because they have angered the builders.',
                    6 => 'So we rebuilt the wall until the entire wall was joined together up to half its height, for the people had the will to keep working.',
                    7 => 'When Sanballat, Tobiah, and the Arabs, Ammonites, and Ashdodites heard that the repair to the walls of Jerusalem was progressing and that the gaps were being closed, they became furious.',
                    8 => 'They all plotted together to come and fight against Jerusalem and throw it into confusion.',
                    9 => 'So we prayed to our God and stationed a guard because of them day and night.',
                    10 => 'In Judah, it was said: The strength of the laborer fails, since there is so much rubble. We will never be able to rebuild the wall.',
                    11 => 'And our enemies said, "They won\'t realize it until we\'re among them and can kill them and stop the work."',
                    12 => 'When the Jews who lived nearby arrived, they said to us time and again, "Everywhere you turn, they attack us."',
                    13 => 'So I stationed people behind the lowest sections of the wall, at the vulnerable areas. I stationed them by families with their swords, spears, and bows.',
                    14 => 'After I made an inspection, I stood up and said to the nobles, the officials, and the rest of the people, "Don\'t be afraid of them. Remember the great and awe-inspiring Lord, and fight for your countrymen, your sons and daughters, your wives and homes."',
                    15 => 'When our enemies heard that we knew their scheme and that God had frustrated it, every one of us returned to his own work on the wall.',
                    16 => 'From that day on, half of my men did the work while the other half held spears, shields, bows, and armor. The officers supported all the people of Judah,',
                    17 => 'who were rebuilding the wall. The laborers who carried the loads worked with one hand and held a weapon with the other.',
                    18 => 'Each of the builders had his sword strapped around his waist while he was building, and the one who sounded the ram\'s horn was beside me.',
                    19 => 'Then I said to the nobles, the officials, and the rest of the people, "The work is enormous and spread out, and we are separated far from one another along the wall.',
                    20 => 'Wherever you hear the sound of the ram\'s horn, rally to us there. Our God will fight for us! "',
                    21 => 'So we continued the work, while half of the men were holding spears from daybreak until the stars came out.',
                    22 => 'At that time, I also said to the people, "Let everyone and his servant spend the night inside Jerusalem, so that they can stand guard by night and work by day."',
                    23 => 'And I, my brothers, my servants, and the men of the guard with me never took off our clothes. Each carried his weapon, even when washing.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                    20 => 2,
                    21 => 2,
                    22 => 2,
                    23 => 2,
                ],
            ],
            5 => [
                'sections' => [
                    1 => 'Social Injustice',
                    2 => 'Good and Bad Governors',
                ],
                'verses' => [
                    1 => 'There was a widespread outcry from the people and their wives against their Jewish countrymen.',
                    2 => 'Some were saying, "We, our sons, and our daughters are numerous. Let us get grain so that we can eat and live."',
                    3 => 'Others were saying, "We are mortgaging our fields, vineyards, and homes to get grain during the famine."',
                    4 => 'Still others were saying, "We have borrowed money to pay the king\'s tax on our fields and vineyards.',
                    5 => 'We and our children are just like our countrymen and their children, yet we are subjecting our sons and daughters to slavery. Some of our daughters are already enslaved, but we are powerless because our fields and vineyards belong to others."',
                    6 => 'I became extremely angry when I heard their outcry and these complaints.',
                    7 => 'After seriously considering the matter, I accused the nobles and officials, saying to them, "Each of you is charging his countrymen interest." So I called a large assembly against them',
                    8 => 'and said, "We have done our best to buy back our Jewish countrymen who were sold to foreigners, but now you sell your own countrymen, and we have to buy them back." They remained silent and could not say a word.',
                    9 => 'Then I said, "What you are doing isn\'t right. Shouldn\'t you walk in the fear of our God and not invite the reproach of our foreign enemies?',
                    10 => 'Even I, as well as my brothers and my servants, have been lending them money and grain. Please, let\'s stop charging this interest.',
                    11 => 'Return their fields, vineyards, olive groves, and houses to them immediately, along with the percentage of the money, grain, new wine, and fresh oil that you have been assessing them."',
                    12 => 'So I summoned the priests and made everyone take an oath to do this.',
                    13 => 'I also shook the folds of my robe and said, "May God likewise shake from his house and property everyone who doesn\'t keep this promise. May he be shaken out and have nothing! " The whole assembly said, "Amen," and they praised the <span class="smallcaps">Lord</span>. Then the people did as they had promised.',
                    14 => 'Furthermore, from the day King Artaxerxes appointed me to be their governor in the land of Judah — from the twentieth year until his thirty-second year, twelve years — I and my associates never ate from the food allotted to the governor.',
                    15 => 'The governors who preceded me had heavily burdened the people, taking from them food and wine as well as a pound of silver. Their subordinates also oppressed the people, but because of the fear of God, I didn\'t do this.',
                    16 => 'Instead, I devoted myself to the construction of this wall, and all my subordinates were gathered there for the work. We didn\'t buy any land.',
                    17 => 'There were 150 Jews and officials, as well as guests from the surrounding nations at my table.',
                    18 => 'Each day, one ox, six choice sheep, and some fowl were prepared for me. An abundance of all kinds of wine was provided every ten days. But I didn\'t demand the food allotted to the governor, because the burden on the people was so heavy.',
                    19 => 'Remember me favorably, my God, for all that I have done for this people.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 2,
                    19 => 2,
                ],
            ],
            6 => [
                'sections' => [
                    1 => 'Attempts to Discourage the Builders',
                    2 => 'Attempts to Intimidate Nehemiah',
                    3 => 'The Wall Completed',
                ],
                'verses' => [
                    1 => 'When Sanballat, Tobiah, Geshem the Arab, and the rest of our enemies heard that I had rebuilt the wall and that no gap was left in it — though at that time I had not installed the doors in the city gates —',
                    2 => 'Sanballat and Geshem sent me a message: "Come, let\'s meet together in the villages of the Ono Valley." They were planning to harm me.',
                    3 => 'So I sent messengers to them, saying, "I am doing important work and cannot come down. Why should the work cease while I leave it and go down to you? "',
                    4 => 'Four times they sent me the same proposal, and I gave them the same reply.',
                    5 => 'Sanballat sent me this same message a fifth time by his aide, who had an open letter in his hand.',
                    6 => 'In it was written:',
                    8 => 'Then I replied to him, "There is nothing to these rumors you are spreading; you are inventing them in your own mind."',
                    9 => 'For they were all trying to intimidate us, saying, "They will drop their hands from the work, and it will never be finished." But now, my God, strengthen my hands.',
                    10 => 'I went to the house of Shemaiah son of Delaiah, son of Mehetabel, who was restricted to his house. He said: Let\'s meet at the house of God, inside the temple. Let\'s shut the temple doors because they\'re coming to kill you. They\'re coming to kill you tonight!',
                    11 => 'But I said, "Should a man like me run away? How can someone like me enter the temple and live? I will not go."',
                    12 => 'I realized that God had not sent him, because of the prophecy he spoke against me. Tobiah and Sanballat had hired him.',
                    13 => 'He was hired, so that I would be intimidated, do as he suggested, sin, and get a bad reputation, in order that they could discredit me.',
                    14 => 'My God, remember Tobiah and Sanballat for what they have done, and also the prophetess Noadiah and the other prophets who wanted to intimidate me.',
                    15 => 'The wall was completed in fifty-two days, on the twenty-fifth day of the month Elul.',
                    16 => 'When all our enemies heard this, all the surrounding nations were intimidated and lost their confidence, for they realized that this task had been accomplished by our God.',
                    17 => 'During those days, the nobles of Judah sent many letters to Tobiah, and Tobiah\'s letters came to them.',
                    18 => 'For many in Judah were bound by oath to him, since he was a son-in-law of Shecaniah son of Arah, and his son Jehohanan had married the daughter of Meshullam son of Berechiah.',
                    19 => 'These nobles kept mentioning Tobiah\'s good deeds to me, and they reported my words to him. And Tobiah sent letters to intimidate me.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 3,
                    16 => 3,
                    17 => 3,
                    18 => 3,
                    19 => 3,
                ],
            ],
            7 => [
                'sections' => [
                    1 => 'The Exiles Return',
                    2 => 'Public Reading of the Law',
                ],
                'verses' => [
                    1 => 'When the wall had been rebuilt and I had the doors installed, the gatekeepers, singers, and Levites were appointed.',
                    2 => 'Then I put my brother Hanani in charge of Jerusalem, along with Hananiah, commander of the fortress, because he was a faithful man who feared God more than most.',
                    3 => 'I said to them, "Do not open the gates of Jerusalem until the sun is hot, and let the doors be shut and securely fastened while the guards are on duty. Station the citizens of Jerusalem as guards, some at their posts and some at their homes."',
                    4 => 'The city was large and spacious, but there were few people in it, and no houses had been built yet.',
                    5 => 'Then my God put it into my mind to assemble the nobles, the officials, and the people to be registered by genealogy. I found the genealogical record of those who came back first, and I found the following written in it:',
                    6 => 'These are the people of the province who went up among the captive exiles deported by King Nebuchadnezzar of Babylon. Each of them returned to Jerusalem and Judah, to his own town.',
                    7 => 'They came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, and Baanah. The number of the Israelite men included',
                    39 => 'The priests included',
                    43 => 'The Levites included',
                    44 => 'The singers included',
                    45 => 'The gatekeepers included',
                    46 => 'The temple servants included',
                    57 => 'The descendants of Solomon\'s servants included',
                    61 => 'The following are those who came from Tel-melah, Tel-harsha, Cherub, Addon, and Immer, but were unable to prove that their ancestral families and their lineage were Israelite:',
                    63 => 'and from the priests: the descendants of Hobaiah, the descendants of Hakkoz, and the descendants of Barzillai — who had taken a wife from the daughters of Barzillai the Gileadite and who bore their name.',
                    64 => 'These searched for their entries in the genealogical records, but they could not be found, so they were disqualified from the priesthood.',
                    65 => 'The governor ordered them not to eat the most holy things until there was a priest who could consult the Urim and Thummim.',
                    70 => 'Some of the family heads contributed to the project. The governor gave 1,000 gold coins, 50 bowls, and 530 priestly garments to the treasury.',
                    71 => 'Some of the family heads gave 20,000 gold coins and 2,200 silver minas to the treasury for the project.',
                    72 => 'The rest of the people gave 20,000 gold coins, 2,000 silver minas, and 67 priestly garments.',
                    73 => 'The priests, Levites, gatekeepers, temple singers, some of the people, temple servants, and all Israel settled in their towns. When the seventh month came and the Israelites had settled in their towns,',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    39 => 1,
                    43 => 1,
                    44 => 1,
                    45 => 1,
                    46 => 1,
                    57 => 1,
                    61 => 1,
                    63 => 1,
                    64 => 1,
                    65 => 1,
                    70 => 1,
                    71 => 1,
                    72 => 1,
                    73 => 1,
                ],
            ],
            8 => [
                'sections' => [
                    1 => 'Festival of Shelters Observed',
                ],
                'verses' => [
                    1 => 'all the people gathered together at the square in front of the Water Gate. They asked the scribe Ezra to bring the book of the law of Moses that the <span class="smallcaps">Lord</span> had given Israel.',
                    2 => 'On the first day of the seventh month, the priest Ezra brought the law before the assembly of men, women, and all who could listen with understanding.',
                    3 => 'While he was facing the square in front of the Water Gate, he read out of it from daybreak until noon before the men, the women, and those who could understand. All the people listened attentively to the book of the law.',
                    4 => 'The scribe Ezra stood on a high wooden platform made for this purpose. Mattithiah, Shema, Anaiah, Uriah, Hilkiah, and Maaseiah stood beside him on his right; to his left were Pedaiah, Mishael, Malchijah, Hashum, Hash-baddanah, Zechariah, and Meshullam.',
                    5 => 'Ezra opened the book in full view of all the people, since he was elevated above everyone. As he opened it, all the people stood up.',
                    6 => 'Ezra blessed the <span class="smallcaps">Lord</span>, the great God, and with their hands uplifted all the people said, "Amen, Amen! " Then they knelt low and worshiped the <span class="smallcaps">Lord</span> with their faces to the ground.',
                    7 => 'Jeshua, Bani, Sherebiah, Jamin, Akkub, Shabbethai, Hodiah, Maaseiah, Kelita, Azariah, Jozabad, Hanan, and Pelaiah, who were Levites, explained the law to the people as they stood in their places.',
                    8 => 'They read out of the book of the law of God, translating and giving the meaning so that the people could understand what was read.',
                    9 => 'Nehemiah the governor, Ezra the priest and scribe, and the Levites who were instructing the people said to all of them, "This day is holy to the <span class="smallcaps">Lord</span> your God. Do not mourn or weep." For all the people were weeping as they heard the words of the law.',
                    10 => 'Then he said to them, "Go and eat what is rich, drink what is sweet, and send portions to those who have nothing prepared, since today is holy to our Lord. Do not grieve, because the joy of the <span class="smallcaps">Lord</span> is your strength."',
                    11 => 'And the Levites quieted all the people, saying, "Be still, since today is holy. Don\'t grieve."',
                    12 => 'Then all the people began to eat and drink, send portions, and have a great celebration, because they had understood the words that were explained to them.',
                    13 => 'On the second day, the family heads of all the people, along with the priests and Levites, assembled before the scribe Ezra to study the words of the law.',
                    14 => 'They found written in the law how the <span class="smallcaps">Lord</span> had commanded through Moses that the Israelites should dwell in shelters during the festival of the seventh month.',
                    15 => 'So they proclaimed and spread this news throughout their towns and in Jerusalem, saying, "Go out to the hill country and bring back branches of olive, wild olive, myrtle, palm, and other leafy trees to make shelters, just as it is written."',
                    16 => 'The people went out, brought back branches, and made shelters for themselves on each of their rooftops and courtyards, the court of the house of God, the square by the Water Gate, and the square by the Ephraim Gate.',
                    17 => 'The whole community that had returned from exile made shelters and lived in them. The Israelites had not celebrated like this from the days of Joshua son of Nun until that day. And there was tremendous joy.',
                    18 => 'Ezra read out of the book of the law of God every day, from the first day to the last. The Israelites celebrated the festival for seven days, and on the eighth day there was a solemn assembly, according to the ordinance.',
                ],
                'versesToSections' => [
                    1 => 0,
                    2 => 0,
                    3 => 0,
                    4 => 0,
                    5 => 0,
                    6 => 0,
                    7 => 0,
                    8 => 0,
                    9 => 0,
                    10 => 0,
                    11 => 0,
                    12 => 0,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                ],
            ],
            9 => [
                'sections' => [
                    1 => 'National Confession of Sin',
                    2 => 'Israel\'s Vow of Faithfulness',
                ],
                'verses' => [
                    1 => 'On the twenty-fourth day of this month the Israelites assembled; they were fasting, wearing sackcloth, and had put dust on their heads.',
                    2 => 'Those of Israelite descent separated themselves from all foreigners, and they stood and confessed their sins and the iniquities of their ancestors.',
                    3 => 'While they stood in their places, they read from the book of the law of the <span class="smallcaps">Lord</span> their God for a fourth of the day and spent another fourth of the day in confession and worship of the <span class="smallcaps">Lord</span> their God.',
                    4 => 'Jeshua, Bani, Kadmiel, Shebaniah, Bunni, Sherebiah, Bani, and Chenani stood on the raised platform built for the Levites and cried out loudly to the <span class="smallcaps">Lord</span> their God.',
                    5 => 'Then the Levites — Jeshua, Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah, and Pethahiah — said, "Stand up. Blessed be the <span class="smallcaps">Lord</span> your God from everlasting to everlasting." Blessed be your glorious name, and may it be exalted above all blessing and praise.',
                    6 => 'You, <span class="smallcaps">Lord</span>, are the only God. You created the heavens, the highest heavens with all their stars, the earth and all that is on it, the seas and all that is in them. You give life to all of them, and all the stars of heaven worship you.',
                    7 => 'You, the <span class="smallcaps">Lord</span>, are the God who chose Abram and brought him out of Ur of the Chaldeans, and changed his name to Abraham.',
                    8 => 'You found his heart faithful in your sight, and made a covenant with him to give the land of the Canaanites, Hethites, Amorites, Perizzites, Jebusites, and Girgashites — to give it to his descendants. You have fulfilled your promise, for you are righteous.',
                    9 => 'You saw the oppression of our ancestors in Egypt and heard their cry at the Red Sea.',
                    10 => 'You performed signs and wonders against Pharaoh, all his officials, and all the people of his land, for you knew how arrogantly they treated our ancestors. You made a name for yourself that endures to this day.',
                    11 => 'You divided the sea before them, and they crossed through it on dry ground. You hurled their pursuers into the depths like a stone into raging water.',
                    12 => 'You led them with a pillar of cloud by day, and with a pillar of fire by night, to illuminate the way they should go.',
                    13 => 'You came down on Mount Sinai, and spoke to them from heaven. You gave them impartial ordinances, reliable instructions, and good statutes and commands.',
                    14 => 'You revealed your holy Sabbath to them, and gave them commands, statutes, and instruction through your servant Moses.',
                    15 => 'You provided bread from heaven for their hunger; you brought them water from the rock for their thirst. You told them to go in and possess the land you had sworn to give them.',
                    16 => 'But our ancestors acted arrogantly; they became stiff-necked and did not listen to your commands.',
                    17 => 'They refused to listen and did not remember your wonders you performed among them. They became stiff-necked and appointed a leader to return to their slavery in Egypt. But you are a forgiving God, gracious and compassionate, slow to anger and abounding in faithful love, and you did not abandon them.',
                    18 => 'Even after they had cast an image of a calf for themselves and said, "This is your god who brought you out of Egypt," and they had committed terrible blasphemies,',
                    19 => 'you did not abandon them in the wilderness because of your great compassion. During the day the pillar of cloud never turned away from them, guiding them on their journey. And during the night the pillar of fire illuminated the way they should go.',
                    20 => 'You sent your good Spirit to instruct them. You did not withhold your manna from their mouths, and you gave them water for their thirst.',
                    21 => 'You provided for them in the wilderness forty years, and they lacked nothing. Their clothes did not wear out, and their feet did not swell.',
                    22 => 'You gave them kingdoms and peoples and established boundaries for them. They took possession of the land of King Sihon of Heshbon and of the land of King Og of Bashan.',
                    23 => 'You multiplied their descendants like the stars of the sky and brought them to the land you told their ancestors to go in and possess.',
                    24 => 'So their descendants went in and possessed the land: You subdued the Canaanites who inhabited the land before them and handed their kings and the surrounding peoples over to them, to do as they pleased with them.',
                    25 => 'They captured fortified cities and fertile land and took possession of well-supplied houses, cisterns cut out of rock, vineyards, olive groves, and fruit trees in abundance. They ate, were filled, became prosperous, and delighted in your great goodness.',
                    26 => 'But they were disobedient and rebelled against you. They flung your law behind their backs and killed your prophets who warned them in order to turn them back to you. They committed terrible blasphemies.',
                    27 => 'So you handed them over to their enemies, who oppressed them. In their time of distress, they cried out to you, and you heard from heaven. In your abundant compassion you gave them deliverers, who rescued them from the power of their enemies.',
                    28 => 'But as soon as they had relief, they again did what was evil in your sight. So you abandoned them to the power of their enemies, who dominated them. When they cried out to you again, you heard from heaven and rescued them many times in your compassion.',
                    29 => 'You warned them to turn back to your law, but they acted arrogantly and would not obey your commands. They sinned against your ordinances, which a person will live by if he does them. They stubbornly resisted, stiffened their necks, and would not obey.',
                    30 => 'You were patient with them for many years, and your Spirit warned them through your prophets, but they would not listen. Therefore, you handed them over to the surrounding peoples.',
                    31 => 'However, in your abundant compassion, you did not destroy them or abandon them, for you are a gracious and compassionate God.',
                    32 => 'So now, our God — the great, mighty, and awe-inspiring God who keeps his gracious covenant — do not view lightly all the hardships that have afflicted us, our kings and leaders, our priests and prophets, our ancestors and all your people, from the days of the Assyrian kings until today.',
                    33 => 'You are righteous concerning all that has happened to us, because you have acted faithfully, while we have acted wickedly.',
                    34 => 'Our kings, leaders, priests, and ancestors did not obey your law or listen to your commands and warnings you gave them.',
                    35 => 'When they were in their kingdom, with your abundant goodness that you gave them, and in the spacious and fertile land you set before them, they would not serve you or turn from their wicked ways.',
                    36 => 'Here we are today, slaves in the land you gave our ancestors so that they could enjoy its fruit and its goodness. Here we are — slaves in it!',
                    37 => 'Its abundant harvest goes to the kings you have set over us, because of our sins. They rule over our bodies and our livestock as they please. We are in great distress.',
                    38 => 'In view of all this, we are making a binding agreement in writing on a sealed document containing the names of our leaders, Levites, and priests.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 1,
                    23 => 1,
                    24 => 1,
                    25 => 1,
                    26 => 1,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                    30 => 1,
                    31 => 1,
                    32 => 1,
                    33 => 1,
                    34 => 1,
                    35 => 1,
                    36 => 1,
                    37 => 1,
                    38 => 2,
                ],
            ],
            10 => [
                'sections' => [
                    1 => 'Details of the Vow',
                ],
                'verses' => [
                    1 => 'Those whose seals were on the document were',
                    28 => 'The rest of the people — the priests, Levites, gatekeepers, singers, and temple servants, along with their wives, sons, and daughters, everyone who is able to understand and who has separated themselves from the surrounding peoples to obey the law of God —',
                    29 => 'join with their noble brothers and commit themselves with a sworn oath to follow the law of God given through God\'s servant Moses and to obey carefully all the commands, ordinances, and statutes of the <span class="smallcaps">Lord</span> our Lord.',
                ],
                'versesToSections' => [
                    1 => 0,
                    28 => 0,
                    29 => 0,
                ],
            ],
            11 => [
                'sections' => [
                    1 => 'Resettling Jerusalem',
                    2 => 'The Levites and Priests',
                ],
                'verses' => [
                    1 => 'Now the leaders of the people stayed in Jerusalem, and the rest of the people cast lots for one out of ten to come and live in Jerusalem, the holy city, while the other nine-tenths remained in their towns.',
                    2 => 'The people blessed all the men who volunteered to live in Jerusalem.',
                    3 => 'These are the heads of the province who stayed in Jerusalem (but in the villages of Judah each lived on his own property in their towns — the Israelites, priests, Levites, temple servants, and descendants of Solomon\'s servants —',
                    4 => 'while some of the descendants of Judah and Benjamin settled in Jerusalem): Judah\'s descendants:',
                    20 => 'The rest of Israel, the priests, and the Levites were in all the villages of Judah, each on his own inherited property.',
                    21 => 'The temple servants lived on Ophel; Ziha and Gishpa supervised the temple servants.',
                    22 => 'The leader of the Levites in Jerusalem was Uzzi son of Bani, son of Hashabiah, son of Mattaniah, son of Mica, of the descendants of Asaph, who were singers for the service of God\'s house.',
                    23 => 'There was, in fact, a command of the king regarding them, and an ordinance regulating the singers\' daily tasks.',
                    24 => 'Pethahiah son of Meshezabel, of the descendants of Zerah son of Judah, was the king\'s agent in every matter concerning the people.',
                    25 => 'As for the farming settlements with their fields:',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 2,
                    23 => 2,
                    24 => 2,
                    25 => 2,
                ],
            ],
            12 => [
                'sections' => [
                    1 => 'Dedication of the Wall',
                    2 => 'Support of the Levites\' Ministry',
                ],
                'verses' => [
                    1 => 'These are the priests and Levites who went up with Zerubbabel son of Shealtiel and with Jeshua:',
                    7 => 'These were the heads of the priests and their relatives in the days of Jeshua.',
                    8 => 'The Levites:',
                    12 => 'In the days of Joiakim, the heads of the priestly families were',
                    22 => 'In the days of Eliashib, Joiada, Johanan, and Jaddua, the heads of the families of the Levites and priests were recorded while Darius the Persian ruled.',
                    23 => 'Levi\'s descendants, the family heads, were recorded in the Book of the Historical Events during the days of Johanan son of Eliashib.',
                    24 => 'The heads of the Levites — Hashabiah, Sherebiah, and Jeshua son of Kadmiel, along with their relatives opposite them — gave praise and thanks, division by division, as David the man of God had prescribed.',
                    25 => 'This included Mattaniah, Bakbukiah, and Obadiah. Meshullam, Talmon, and Akkub were gatekeepers who guarded the storerooms at the city gates.',
                    26 => 'These served in the days of Joiakim son of Jeshua, son of Jozadak, and in the days of Nehemiah the governor and Ezra the priest and scribe.',
                    27 => 'At the dedication of the wall of Jerusalem, they sent for the Levites wherever they lived and brought them to Jerusalem to celebrate the joyous dedication with thanksgiving and singing accompanied by cymbals, harps, and lyres.',
                    28 => 'The singers gathered from the region around Jerusalem, from the settlements of the Netophathites,',
                    29 => 'from Beth-gilgal, and from the fields of Geba and Azmaveth, for they had built settlements for themselves around Jerusalem.',
                    30 => 'After the priests and Levites had purified themselves, they purified the people, the city gates, and the wall.',
                    31 => 'Then I brought the leaders of Judah up on top of the wall, and I appointed two large processions that gave thanks. One went to the right on the wall, toward the Dung Gate.',
                    32 => 'Hoshaiah and half the leaders of Judah followed,',
                    33 => 'along with Azariah, Ezra, Meshullam,',
                    34 => 'Judah, Benjamin, Shemaiah, Jeremiah,',
                    35 => 'and some of the priests\' sons with trumpets, and Zechariah son of Jonathan, son of Shemaiah, son of Mattaniah, son of Micaiah, son of Zaccur, son of Asaph followed',
                    36 => 'as well as his relatives — Shemaiah, Azarel, Milalai, Gilalai, Maai, Nethanel, Judah, and Hanani, with the musical instruments of David, the man of God. Ezra the scribe went in front of them.',
                    37 => 'At the Fountain Gate they climbed the steps of the city of David on the ascent of the wall and went above the house of David to the Water Gate on the east.',
                    38 => 'The second thanksgiving procession went to the left, and I followed it with half the people along the top of the wall, past the Tower of the Ovens to the Broad Wall,',
                    39 => 'above the Ephraim Gate, and by the Old Gate, the Fish Gate, the Tower of Hananel, and the Tower of the Hundred, to the Sheep Gate. They stopped at the Gate of the Guard.',
                    40 => 'The two thanksgiving processions stood in the house of God. So did I and half of the officials accompanying me,',
                    41 => 'as well as the priests:',
                    42 => 'Then the singers sang, with Jezrahiah as the leader.',
                    43 => 'On that day they offered great sacrifices and rejoiced because God had given them great joy. The women and children also celebrated, and Jerusalem\'s rejoicing was heard far away.',
                    44 => 'On that same day men were placed in charge of the rooms that housed the supplies, contributions, firstfruits, and tenths. The legally required portions for the priests and Levites were gathered from the village fields, because Judah was grateful to the priests and Levites who were serving.',
                    45 => 'They performed the service of their God and the service of purification, along with the singers and gatekeepers, as David and his son Solomon had prescribed.',
                    46 => 'For long ago, in the days of David and Asaph, there were heads of the singers and songs of praise and thanksgiving to God.',
                    47 => 'So in the days of Zerubbabel and Nehemiah, all Israel contributed the daily portions for the singers and gatekeepers. They also set aside daily portions for the Levites, and the Levites set aside daily portions for Aaron\'s descendants.',
                ],
                'versesToSections' => [
                    1 => 0,
                    7 => 0,
                    8 => 0,
                    12 => 0,
                    22 => 0,
                    23 => 0,
                    24 => 0,
                    25 => 0,
                    26 => 0,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                    30 => 1,
                    31 => 1,
                    32 => 1,
                    33 => 1,
                    34 => 1,
                    35 => 1,
                    36 => 1,
                    37 => 1,
                    38 => 1,
                    39 => 1,
                    40 => 1,
                    41 => 1,
                    42 => 1,
                    43 => 1,
                    44 => 2,
                    45 => 2,
                    46 => 2,
                    47 => 2,
                ],
            ],
            13 => [
                'sections' => [
                    1 => 'Nehemiah\'s Further Reforms',
                ],
                'verses' => [
                    1 => 'At that time the book of Moses was read publicly to the people. The command was found written in it that no Ammonite or Moabite should ever enter the assembly of God,',
                    2 => 'because they did not meet the Israelites with food and water. Instead, they hired Balaam against them to curse them, but our God turned the curse into a blessing.',
                    3 => 'When they heard the law, they separated all those of mixed descent from Israel.',
                    4 => 'Now before this, the priest Eliashib had been put in charge of the storerooms of the house of our God. He was a relative of Tobiah',
                    5 => 'and had prepared a large room for him where they had previously stored the grain offerings, the frankincense, the articles, and the tenths of grain, new wine, and fresh oil prescribed for the Levites, singers, and gatekeepers, along with the contributions for the priests.',
                    6 => 'While all this was happening, I was not in Jerusalem, because I had returned to King Artaxerxes of Babylon in the thirty-second year of his reign. It was only later that I asked the king for a leave of absence',
                    7 => 'so I could return to Jerusalem. Then I discovered the evil that Eliashib had done on behalf of Tobiah by providing him a room in the courts of God\'s house.',
                    8 => 'I was greatly displeased and threw all of Tobiah\'s household possessions out of the room.',
                    9 => 'I ordered that the rooms be purified, and I had the articles of the house of God restored there, along with the grain offering and frankincense.',
                    10 => 'I also found out that because the portions for the Levites had not been given, each of the Levites and the singers performing the service had gone back to his own field.',
                    11 => 'Therefore, I rebuked the officials, asking, "Why has the house of God been neglected? " I gathered the Levites and singers together and stationed them at their posts.',
                    12 => 'Then all Judah brought a tenth of the grain, new wine, and fresh oil into the storehouses.',
                    13 => 'I appointed as treasurers over the storehouses the priest Shelemiah, the scribe Zadok, and Pedaiah of the Levites, with Hanan son of Zaccur, son of Mattaniah to assist them, because they were considered trustworthy. They were responsible for the distribution to their colleagues.',
                    14 => 'Remember me for this, my God, and don\'t erase the deeds of faithful love I have done for the house of my God and for its services.',
                    15 => 'At that time I saw people in Judah treading winepresses on the Sabbath. They were also bringing in stores of grain and loading them on donkeys, along with wine, grapes, and figs. All kinds of goods were being brought to Jerusalem on the Sabbath day. So I warned them against selling food on that day.',
                    16 => 'The Tyrians living there were importing fish and all kinds of merchandise and selling them on the Sabbath to the people of Judah in Jerusalem.',
                    17 => 'I rebuked the nobles of Judah and said to them, "What is this evil you are doing — profaning the Sabbath day?',
                    18 => 'Didn\'t your ancestors do the same, so that our God brought all this disaster on us and on this city? And now you are rekindling his anger against Israel by profaning the Sabbath! "',
                    19 => 'When shadows began to fall on the city gates of Jerusalem just before the Sabbath, I gave orders that the city gates be closed and not opened until after the Sabbath. I posted some of my men at the gates, so that no goods could enter during the Sabbath day.',
                    20 => 'Once or twice the merchants and those who sell all kinds of goods camped outside Jerusalem,',
                    21 => 'but I warned them, "Why are you camping in front of the wall? If you do it again, I\'ll use force against you." After that they did not come again on the Sabbath.',
                    22 => 'Then I instructed the Levites to purify themselves and guard the city gates in order to keep the Sabbath day holy. Remember me for this also, my God, and look on me with compassion according to the abundance of your faithful love.',
                    23 => 'In those days I also saw Jews who had married women from Ashdod, Ammon, and Moab.',
                    24 => 'Half of their children spoke the language of Ashdod or the language of one of the other peoples but could not speak Hebrew.',
                    25 => 'I rebuked them, cursed them, beat some of their men, and pulled out their hair. I forced them to take an oath before God and said, "You must not give your daughters in marriage to their sons or take their daughters as wives for your sons or yourselves!',
                    26 => 'Didn\'t King Solomon of Israel sin in matters like this? There was not a king like him among many nations. He was loved by his God, and God made him king over all Israel, yet foreign women drew him into sin.',
                    27 => 'Why then should we hear about you doing all this terrible evil and acting unfaithfully against our God by marrying foreign women? "',
                    28 => 'Even one of the sons of Jehoiada, son of the high priest Eliashib, had become a son-in-law to Sanballat the Horonite. So I drove him away from me.',
                    29 => 'Remember them, my God, for defiling the priesthood as well as the covenant of the priesthood and the Levites.',
                    30 => 'So I purified them from everything foreign and assigned specific duties to each of the priests and Levites.',
                    31 => 'I also arranged for the donation of wood at the appointed times and for the firstfruits. Remember me, my God, with favor.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 1,
                    23 => 1,
                    24 => 1,
                    25 => 1,
                    26 => 1,
                    27 => 1,
                    28 => 1,
                    29 => 1,
                    30 => 1,
                    31 => 1,
                ],
            ],
        ];
    }
} 