<?php

declare(strict_types=1);

namespace BKuhl\BibleCSB\Book;

use BKuhl\BibleCSB\Book;
use BKuhl\BibleCSB\Testament;

class Zechariah extends Book
{
    private const ABBREVIATION = 'Zech';
    public const ID = 38;

    public function testament(): Testament
    {
        return Testament::OLD;
    }

    public function name(): string
    {
        return 'Zechariah';
    }

    public function position(): int
    {
        return self::ID;
    }

    public function abbreviation(): string
    {
        return self::ABBREVIATION;
    }

    /**
     * @return array<int, array{sections: array<int, string>, verses: array<int, string>, versesToSections: array<int, int>}>
     */
    protected function getChapterData(): array
    {
        return [
            1 => [
                'sections' => [
                    1 => 'A Plea for Repentance',
                    2 => 'First Vision: Horsemen',
                    3 => 'Second Vision: Four Horns and Craftsmen',
                ],
                'verses' => [
                    1 => 'In the eighth month, in the second year of Darius, the word of the Lord came to the prophet Zechariah son of Berechiah, son of Iddo:',
                    2 => '"The was extremely angry with your ancestors.',
                    3 => 'So tell the people, \'This is what the Lord of Armies says: Return to me — this is the declaration of the Lord of Armies — and I will return to you, says the Lord of Armies.',
                    4 => 'Do not be like your ancestors; the earlier prophets proclaimed to them: This is what the Lord of Armies says: Turn from your evil ways and your evil deeds. But they did not listen or pay attention to me — this is the Lord\'s declaration.',
                    5 => 'Where are your ancestors now? And do the prophets live forever?',
                    6 => 'But didn\'t my words and my statutes that I commanded my servants the prophets overtake your ancestors? \' "',
                    7 => 'On the twenty-fourth day of the eleventh month, which is the month of Shebat, in the second year of Darius, the word of the Lord came to the prophet Zechariah son of Berechiah, son of Iddo:',
                    8 => 'I looked out in the night and saw a man riding on a chestnut horse. He was standing among the myrtle trees in the valley. Behind him were chestnut, brown, and white horses.',
                    9 => 'I asked, "What are these, my lord? "',
                    10 => 'Then the man standing among the myrtle trees explained, "They are the ones the has sent to patrol the earth."',
                    11 => 'They reported to the angel of the Lord standing among the myrtle trees, "We have patrolled the earth, and right now the whole earth is calm and quiet."',
                    12 => 'Then the angel of the Lord responded, "How long, of Armies, will you withhold mercy from Jerusalem and the cities of Judah that you have been angry with these seventy years? "',
                    13 => 'The replied with kind and comforting words to the angel who was speaking with me.',
                    14 => 'So the angel who was speaking with me said, "Proclaim: The Lord of Armies says: I am extremely jealous for Jerusalem and Zion.',
                    15 => 'I am fiercely angry with the nations that are at ease, for I was a little angry, but they made the destruction worse.',
                    16 => 'Therefore, this is what the Lord says: In mercy, I have returned to Jerusalem; my house will be rebuilt within it — this is the declaration of the Lord of Armies — and a measuring line will be stretched out over Jerusalem.',
                    17 => '"Proclaim further: This is what the Lord of Armies says: My cities will again overflow with prosperity; the Lord will once more comfort Zion and again choose Jerusalem."',
                    18 => 'Then I looked up and saw four horns.',
                    19 => 'So I asked the angel who was speaking with me, "What are these? "',
                    20 => 'Then the Lord showed me four craftsmen.',
                    21 => 'I asked, "What are they coming to do? "',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 2,
                    9 => 2,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                    16 => 2,
                    17 => 2,
                    18 => 3,
                    19 => 3,
                    20 => 3,
                    21 => 3,
                ],
            ],
            2 => [
                'sections' => [
                    1 => 'Third Vision: Surveyor',
                ],
                'verses' => [
                    1 => 'I looked up and saw a man with a measuring line in his hand.',
                    2 => 'I asked, "Where are you going? "',
                    3 => 'Then the angel who was speaking with me went out, and another angel went out to meet him.',
                    4 => 'He said to him, "Run and tell this young man: Jerusalem will be inhabited without walls because of the number of people and animals in it."',
                    5 => 'The declaration of the Lord: "I myself will be a wall of fire around it, and I will be the glory within it."',
                    6 => '"Listen! Listen! Flee from the land of the north" — this is the Lord\'s declaration — "for I have scattered you like the four winds of heaven" — this is the Lord\'s declaration.',
                    7 => '"Listen, Zion! Escape, you who are living with Daughter Babylon."',
                    8 => 'For the of Armies says this: "In pursuit of his glory, he sent me against the nations plundering you, for whoever touches you touches the pupil of my eye.',
                    9 => 'For look, I am raising my hand against them, and they will become plunder for their own servants. Then you will know that the Lord of Armies has sent me.',
                    10 => '"Daughter Zion, shout for joy and be glad, for I am coming to dwell among you" — this is the Lord\'s declaration.',
                    11 => '"Many nations will join themselves to the Lord on that day and become my people. I will dwell among you, and you will know that the Lord of Armies has sent me to you.',
                    12 => 'The will take possession of Judah as his portion in the Holy Land, and he will once again choose Jerusalem.',
                    13 => 'Let all humanity be silent before the Lord, for from his holy dwelling he has roused himself."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                ],
            ],
            3 => [
                'sections' => [
                    1 => 'Fourth Vision: High Priest and Branch',
                ],
                'verses' => [
                    1 => 'Then he showed me the high priest Joshua standing before the angel of the Lord, with Satan standing at his right side to accuse him.',
                    2 => 'The Lord said to Satan, "The Lord rebuke you, Satan! May the who has chosen Jerusalem rebuke you! Isn\'t this man a burning stick snatched from the fire? "',
                    3 => 'Now Joshua was dressed with filthy clothes as he stood before the angel.',
                    4 => 'So the angel of the Lord spoke to those standing before him, "Take off his filthy clothes! " Then he said to him, "See, I have removed your iniquity from you, and I will clothe you with festive robes."',
                    5 => 'Then I said, "Let them put a clean turban on his head." So a clean turban was placed on his head, and they clothed him in garments while the angel of the Lord was standing nearby.',
                    6 => 'Then the angel of the Lord charged Joshua,',
                    7 => '"This is what the Lord of Armies says: If you walk in my ways and keep my mandates, you will both rule my house and take care of my courts; I will also grant you access among these who are standing here.',
                    8 => '"Listen, High Priest Joshua, you and your colleagues sitting before you; indeed, these men are a sign that I am about to bring my servant, the Branch.',
                    9 => 'Notice the stone I have set before Joshua; on that one stone are seven eyes. I will engrave an inscription on it" — this is the declaration of the Lord of Armies — "and I will take away the iniquity of this land in a single day.',
                    10 => 'On that day, each of you will invite his neighbor to sit under his vine and fig tree." This is the declaration of the Lord of Armies.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                ],
            ],
            4 => [
                'sections' => [
                    1 => 'Fifth Vision: Gold Lampstand',
                ],
                'verses' => [
                    1 => 'The angel who was speaking with me then returned and roused me as one awakened out of sleep.',
                    2 => 'I replied, "I see a solid gold lampstand with a bowl at the top. The lampstand also has seven lamps at the top with seven spouts for each of the lamps.',
                    3 => 'There are also two olive trees beside it, one on the right of the bowl and the other on its left."',
                    4 => 'Then I asked the angel who was speaking with me, "What are these, my lord? "',
                    5 => '"Don\'t you know what they are? " replied the angel who was speaking with me.',
                    6 => 'So he answered me, "This is the word of the Lord to Zerubbabel: \'Not by strength or by might, but by my Spirit,\' says the Lord of Armies.',
                    7 => '\'What are you, great mountain? Before Zerubbabel you will become a plain. And he will bring out the capstone accompanied by shouts of: Grace, grace to it! \' "',
                    8 => 'Then the word of the Lord came to me:',
                    9 => '"Zerubbabel\'s hands have laid the foundation of this house, and his hands will complete it. Then you will know that the Lord of Armies has sent me to you.',
                    10 => 'For who despises the day of small things? These seven eyes of the Lord, which scan throughout the whole earth, will rejoice when they see the ceremonial stone in Zerubbabel\'s hand."',
                    11 => 'I asked him, "What are the two olive trees on the right and left of the lampstand? "',
                    12 => 'And I questioned him further, "What are the two streams of the olive trees, from which the golden oil is pouring through the two golden conduits? "',
                    13 => 'Then he inquired of me, "Don\'t you know what these are? "',
                    14 => '"These are the two anointed ones," he said, "who stand by the Lord of the whole earth."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                ],
            ],
            5 => [
                'sections' => [
                    1 => 'Sixth Vision: Flying Scroll',
                    2 => 'Seventh Vision: Woman in the Basket',
                ],
                'verses' => [
                    1 => 'I looked up again and saw a flying scroll.',
                    2 => '"What do you see? " he asked me.',
                    3 => 'Then he said to me, "This is the curse that is going out over the whole land, for everyone who is a thief, contrary to what is written on one side, has gone unpunished, and everyone who swears falsely, contrary to what is written on the other side, has gone unpunished.',
                    4 => 'I will send it out," — this is the declaration of the Lord of Armies — "and it will enter the house of the thief and the house of the one who swears falsely by my name. It will stay inside his house and destroy it along with its timbers and stones."',
                    5 => 'Then the angel who was speaking with me came forward and told me, "Look up and see what this is that is approaching."',
                    6 => 'He responded, "It\'s a measuring basket that is approaching." And he continued, "This is their iniquity in all the land."',
                    7 => 'Then a lead cover was lifted, and there was a woman sitting inside the basket.',
                    8 => '"This is Wickedness," he said. He shoved her down into the basket and pushed the lead weight over its opening.',
                    9 => 'Then I looked up and saw two women approaching with the wind in their wings. Their wings were like those of a stork, and they lifted up the basket between earth and sky.',
                    10 => 'So I asked the angel who was speaking with me, "Where are they taking the basket? "',
                    11 => '"To build a shrine for it in the land of Shinar," he told me. "When that is ready, the basket will be placed there on its pedestal."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 2,
                    6 => 2,
                    7 => 2,
                    8 => 2,
                    9 => 2,
                    10 => 2,
                    11 => 2,
                ],
            ],
            6 => [
                'sections' => [
                    1 => 'Eighth Vision: Four Chariots',
                    2 => 'Crowning of the Branch',
                ],
                'verses' => [
                    1 => 'Then I looked up again and saw four chariots coming from between two mountains. The mountains were made of bronze.',
                    2 => 'The first chariot had chestnut horses, the second chariot black horses,',
                    3 => 'the third chariot white horses, and the fourth chariot dappled horses — all strong horses.',
                    4 => 'So I inquired of the angel who was speaking with me, "What are these, my lord? "',
                    5 => 'The angel told me, "These are the four spirits of heaven going out after presenting themselves to the Lord of the whole earth.',
                    6 => 'The one with the black horses is going to the land of the north, the white horses are going after them, but the dappled horses are going to the land of the south."',
                    7 => 'As the strong horses went out, they wanted to go patrol the earth, and the Lord said, "Go, patrol the earth." So they patrolled the earth.',
                    8 => 'Then he summoned me saying, "See, those going to the land of the north have pacified my Spirit in the northern land."',
                    9 => 'The word of the came to me:',
                    10 => '"Take an offering from the exiles, from Heldai, Tobijah, and Jedaiah, who have arrived from Babylon, and go that same day to the house of Josiah son of Zephaniah.',
                    11 => 'Take silver and gold, make a crown, and place it on the head of Joshua son of Jehozadak, the high priest.',
                    12 => 'You are to tell him: This is what the Lord of Armies says: Here is a man whose name is Branch; he will branch out from his place and build the Lord\'s temple.',
                    13 => 'Yes, he will build the Lord\'s temple; he will bear royal splendor and will sit on his throne and rule. There will be a priest on his throne, and there will be peaceful counsel between the two of them.',
                    14 => 'The crown will reside in the Lord\'s temple as a memorial to Heldai, Tobijah, Jedaiah, and Hen son of Zephaniah.',
                    15 => 'People who are far off will come and build the Lord\'s temple, and you will know that the Lord of Armies has sent me to you. This will happen when you fully obey the your God."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 2,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                    15 => 2,
                ],
            ],
            7 => [
                'sections' => [
                    1 => 'Disobedience and Fasting',
                ],
                'verses' => [
                    1 => 'In the fourth year of King Darius, the word of the Lord came to Zechariah on the fourth day of the ninth month, which is Chislev.',
                    2 => 'Now the people of Bethel had sent Sharezer, Regem-melech, and their men to plead for the Lord\'s favor',
                    3 => 'by asking the priests who were at the house of the Lord of Armies as well as the prophets, "Should we mourn and fast in the fifth month as we have done these many years? "',
                    4 => 'Then the word of the Lord of Armies came to me:',
                    5 => '"Ask all the people of the land and the priests: When you fasted and lamented in the fifth and in the seventh months for these seventy years, did you really fast for me?',
                    6 => 'When you eat and drink, don\'t you eat and drink simply for yourselves?',
                    7 => 'Aren\'t these the words that the Lord proclaimed through the earlier prophets when Jerusalem was inhabited and secure, along with its surrounding cities, and when the southern region and the Judean foothills were inhabited? "',
                    8 => 'The word of the came to Zechariah:',
                    9 => '"The of Armies says this: \'Make fair decisions. Show faithful love and compassion to one another.',
                    10 => 'Do not oppress the widow or the fatherless, the resident alien or the poor, and do not plot evil in your hearts against one another.\'',
                    11 => 'But they refused to pay attention and turned a stubborn shoulder; they closed their ears so they could not hear.',
                    12 => 'They made their hearts like a rock so as not to obey the law or the words that the Lord of Armies had sent by his Spirit through the earlier prophets. Therefore intense anger came from the Lord of Armies.',
                    13 => 'Just as he had called, and they would not listen, so when they called, I would not listen, says the of Armies.',
                    14 => 'I scattered them with a windstorm over all the nations that had not known them, and the land was left desolate behind them, with no one coming or going. They turned a pleasant land into a desolation."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                ],
            ],
            8 => [
                'sections' => [
                    1 => 'Obedience and Feasting',
                ],
                'verses' => [
                    1 => 'The word of the Lord of Armies came:',
                    2 => 'The of Armies says this: "I am extremely jealous for Zion; I am jealous for her with great wrath."',
                    3 => 'The says this: "I will return to Zion and live in Jerusalem. Then Jerusalem will be called the Faithful City; the mountain of the Lord of Armies will be called the Holy Mountain."',
                    4 => 'The of Armies says this: "Old men and women will again sit along the streets of Jerusalem, each with a staff in hand because of advanced age.',
                    5 => 'The streets of the city will be filled with boys and girls playing in them."',
                    6 => 'The of Armies says this: "Though it may seem impossible to the remnant of this people in those days, should it also seem impossible to me? " — this is the declaration of the Lord of Armies.',
                    7 => 'The of Armies says this: "I will save my people from the land of the east and the land of the west.',
                    8 => 'I will bring them back to live in Jerusalem. They will be my people, and I will be their faithful and righteous God."',
                    9 => 'The of Armies says this: "Let your hands be strong, you who now hear these words that the prophets spoke when the foundations were laid for the rebuilding of the temple, the house of the of Armies.',
                    10 => 'For prior to those days neither people nor animals had wages. There was no safety from the enemy for anyone who came or went, for I turned everyone against his neighbor.',
                    11 => 'But now, I will not treat the remnant of this people as in the former days" — this is the declaration of the Lord of Armies.',
                    12 => '"For they will sow in peace: the vine will yield its fruit, the land will yield its produce, and the skies will yield their dew. I will give the remnant of this people all these things as an inheritance.',
                    13 => 'As you have been a curse among the nations, house of Judah and house of Israel, so I will save you, and you will be a blessing. Don\'t be afraid; let your hands be strong."',
                    14 => 'For the of Armies says this: "As I resolved to treat you badly when your ancestors provoked me to anger, and I did not relent," says the Lord of Armies,',
                    15 => '"so I have resolved again in these days to do what is good to Jerusalem and the house of Judah. Don\'t be afraid.',
                    16 => 'These are the things you must do: Speak truth to one another; make true and sound decisions within your city gates.',
                    17 => 'Do not plot evil in your hearts against your neighbor, and do not love perjury, for I hate all this" — this is the Lord\'s declaration.',
                    18 => 'Then the word of the Lord of Armies came to me:',
                    19 => 'The of Armies says this: "The fast of the fourth month, the fast of the fifth, the fast of the seventh, and the fast of the tenth will become times of joy, gladness, and cheerful festivals for the house of Judah. Therefore, love truth and peace."',
                    20 => 'The of Armies says this: "Peoples will yet come, the residents of many cities;',
                    21 => 'the residents of one city will go to another, saying: Let\'s go at once to plead for the Lord\'s favor and to seek the Lord of Armies. I am also going.',
                    22 => 'Many peoples and strong nations will come to seek the Lord of Armies in Jerusalem and to plead for the Lord\'s favor."',
                    23 => 'The of Armies says this: "In those days, ten men from nations of every language will grab the robe of a Jewish man tightly, urging: Let us go with you, for we have heard that God is with you."',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                    22 => 1,
                    23 => 1,
                ],
            ],
            9 => [
                'sections' => [
                    1 => 'Judgment of Zion\'s Enemies',
                    2 => 'The Coming of Zion\'s King',
                ],
                'verses' => [
                    1 => 'A pronouncement:',
                ],
                'versesToSections' => [
                    1 => 1,
                ],
            ],
            10 => [
                'sections' => [
                    1 => 'The Restores His People',
                ],
                'verses' => [
                ],
                'versesToSections' => [
                ],
            ],
            11 => [
                'sections' => [
                    1 => 'Israel\'s Shepherds: Good and Bad',
                ],
                'verses' => [
                    4 => 'The my God says this: "Shepherd the flock intended for slaughter.',
                    5 => 'Those who buy them slaughter them but are not punished. Those who sell them say, \'Blessed be the Lord because I have become rich!\' Even their own shepherds have no compassion for them.',
                    6 => 'Indeed, I will no longer have compassion on the inhabitants of the land" — this is the Lord\'s declaration. "Instead, I will turn everyone over to his neighbor and his king. They will devastate the land, and I will not rescue it from their hand."',
                    7 => 'So I shepherded the flock intended for slaughter, the oppressed of the flock. I took two staffs, calling one Favor and the other Union, and I shepherded the flock.',
                    8 => 'In one month I got rid of three shepherds. I became impatient with them, and they also detested me.',
                    9 => 'Then I said, "I will no longer shepherd you. Let what is dying die, and let what is perishing perish; let the rest devour each other\'s flesh."',
                    10 => 'Next I took my staff called Favor and cut it in two, annulling the covenant I had made with all the peoples.',
                    11 => 'It was annulled on that day, and so the oppressed of the flock who were watching me knew that it was the word of the Lord.',
                    12 => 'Then I said to them, "If it seems right to you, give me my wages; but if not, keep them." So they weighed my wages, thirty pieces of silver.',
                    13 => '"Throw it to the potter," the Lord said to me — this magnificent price I was valued by them. So I took the thirty pieces of silver and threw it into the house of the Lord, to the potter.',
                    14 => 'Then I cut in two my second staff, Union, annulling the brotherhood between Judah and Israel.',
                    15 => 'The also said to me, "Take the equipment of a foolish shepherd.',
                    16 => 'I am about to raise up a shepherd in the land who will not care for those who are perishing, and he will not seek the lost or heal the broken. He will not sustain the healthy, but he will devour the flesh of the fat sheep and tear off their hooves.',
                ],
                'versesToSections' => [
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                ],
            ],
            12 => [
                'sections' => [
                    1 => 'Judah\'s Security',
                    2 => 'Mourning for the Pierced One',
                ],
                'verses' => [
                    1 => 'A pronouncement:',
                    2 => '"Look, I will make Jerusalem a cup that causes staggering for the peoples who surround the city. The siege against Jerusalem will also involve Judah.',
                    3 => 'On that day I will make Jerusalem a heavy stone for all the peoples; all who try to lift it will injure themselves severely when all the nations of the earth gather against her.',
                    4 => 'On that day" — this is the Lord\'s declaration — "I will strike every horse with panic and its rider with madness. I will keep a watchful eye on the house of Judah but strike all the horses of the nations with blindness.',
                    5 => 'Then each of the leaders of Judah will think to himself: The residents of Jerusalem are my strength through the of Armies, their God.',
                    6 => 'On that day I will make the leaders of Judah like a firepot in a woodpile, like a flaming torch among sheaves; they will consume all the peoples around them on the right and the left, while Jerusalem continues to be inhabited on its site, in Jerusalem.',
                    7 => 'The will save the tents of Judah first, so that the glory of David\'s house and the glory of Jerusalem\'s residents may not be greater than that of Judah.',
                    8 => 'On that day the Lord will defend the inhabitants of Jerusalem, so that on that day the one who is weakest among them will be like David on that day, and the house of David will be like God, like the angel of the Lord, before them.',
                    9 => 'On that day I will set out to destroy all the nations that come against Jerusalem.',
                    10 => '"Then I will pour out a spirit of grace and prayer on the house of David and the residents of Jerusalem, and they will look at me whom they pierced. They will mourn for him as one mourns for an only child and weep bitterly for him as one weeps for a firstborn.',
                    11 => 'On that day the mourning in Jerusalem will be as great as the mourning of Hadad-rimmon in the plain of Megiddo.',
                    12 => 'The land will mourn, every family by itself: the family of David\'s house by itself and their women by themselves; the family of Nathan\'s house by itself and their women by themselves;',
                    13 => 'the family of Levi\'s house by itself and their women by themselves; the family of Shimei by itself and their women by themselves;',
                    14 => 'all the remaining families, every family by itself, and their women by themselves.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 2,
                    11 => 2,
                    12 => 2,
                    13 => 2,
                    14 => 2,
                ],
            ],
            13 => [
                'sections' => [
                    1 => 'God\'s People Cleansed',
                ],
                'verses' => [
                    1 => '"On that day a fountain will be opened for the house of David and for the residents of Jerusalem, to wash away sin and impurity.',
                    2 => 'On that day" — this is the declaration of the Lord of Armies — "I will remove the names of the idols from the land, and they will no longer be remembered. I will banish the prophets and the unclean spirit from the land.',
                    3 => 'If a man still prophesies, his father and his mother who bore him will say to him, \'You cannot remain alive because you have spoken a lie in the name of the Lord.\' When he prophesies, his father and his mother who bore him will pierce him through.',
                    4 => 'On that day every prophet will be ashamed of his vision when he prophesies; they will not put on a hairy cloak in order to deceive.',
                    5 => 'He will say, \'I am not a prophet; I work the land, for a man purchased me as a servant since my youth.\'',
                    6 => 'If someone asks him, \'What are these wounds on your chest?\' — then he will answer, \'I received the wounds in the house of my friends.\'',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                ],
            ],
            14 => [
                'sections' => [
                    1 => 'The \'s Triumph and Reign',
                ],
                'verses' => [
                    1 => 'Look, a day belonging to the Lord is coming when the plunder taken from you will be divided in your presence.',
                    2 => 'I will gather all the nations against Jerusalem for battle. The city will be captured, the houses looted, and the women raped. Half the city will go into exile, but the rest of the people will not be removed from the city.',
                    3 => 'Then the will go out to fight against those nations as he fights on a day of battle.',
                    4 => 'On that day his feet will stand on the Mount of Olives, which faces Jerusalem on the east. The Mount of Olives will be split in half from east to west, forming a huge valley, so that half the mountain will move to the north and half to the south.',
                    5 => 'You will flee by my mountain valley, for the valley of the mountains will extend to Azal. You will flee as you fled from the earthquake in the days of King Uzziah of Judah. Then the Lord my God will come and all the holy ones with him.',
                    6 => 'On that day there will be no light; the sunlight and moonlight will diminish.',
                    7 => 'It will be a unique day known only to the Lord, without day or night, but there will be light at evening.',
                    8 => 'On that day living water will flow out from Jerusalem, half of it toward the eastern sea and the other half toward the western sea, in summer and winter alike.',
                    9 => 'On that day the Lord will become King over the whole earth — the Lord alone, and his name alone.',
                    10 => 'All the land from Geba to Rimmon south of Jerusalem will be changed into a plain. But Jerusalem will be raised up and will remain on its site from the Benjamin Gate to the place of the First Gate, to the Corner Gate, and from the Tower of Hananel to the royal winepresses.',
                    11 => 'People will live there, and never again will there be a curse of complete destruction. So Jerusalem will dwell in security.',
                    12 => 'This will be the plague with which the Lord strikes all the people who have warred against Jerusalem: their flesh will rot while they stand on their feet, their eyes will rot in their sockets, and their tongues will rot in their mouths.',
                    13 => 'On that day a great panic from the Lord will be among them, so that each will seize the hand of another, and the hand of one will rise against the other.',
                    14 => 'Judah will also fight at Jerusalem, and the wealth of all the surrounding nations will be collected: gold, silver, and clothing in great abundance.',
                    15 => 'The same plague as the previous one will strike the horses, mules, camels, donkeys, and all the animals that are in those camps.',
                    16 => 'Then all the survivors from the nations that came against Jerusalem will go up year after year to worship the King, the of Armies, and to celebrate the Festival of Shelters.',
                    17 => 'Should any of the families of the earth not go up to Jerusalem to worship the King, the of Armies, rain will not fall on them.',
                    18 => 'And if the people of Egypt will not go up and enter, then rain will not fall on them; this will be the plague the inflicts on the nations who do not go up to celebrate the Festival of Shelters.',
                    19 => 'This will be the punishment of Egypt and all the nations that do not go up to celebrate the Festival of Shelters.',
                    20 => 'On that day, the words H Lord will be on the bells of the horses. The pots in the house of the Lord will be like the sprinkling basins before the altar.',
                    21 => 'Every pot in Jerusalem and in Judah will be holy to the Lord of Armies. All who sacrifice will come and use the pots to cook in. And on that day there will no longer be a Canaanite in the house of the Lord of Armies.',
                ],
                'versesToSections' => [
                    1 => 1,
                    2 => 1,
                    3 => 1,
                    4 => 1,
                    5 => 1,
                    6 => 1,
                    7 => 1,
                    8 => 1,
                    9 => 1,
                    10 => 1,
                    11 => 1,
                    12 => 1,
                    13 => 1,
                    14 => 1,
                    15 => 1,
                    16 => 1,
                    17 => 1,
                    18 => 1,
                    19 => 1,
                    20 => 1,
                    21 => 1,
                ],
            ],
        ];
    }
} 