<?php

declare(strict_types=1);

namespace BKuhl\BibleCSB;

use BKuhl\BibleCSB\Book\Acts;
use BKuhl\BibleCSB\Book\Amos;
use BKuhl\BibleCSB\Book\Colossians;
use BKuhl\BibleCSB\Book\Daniel;
use BKuhl\BibleCSB\Book\Deuteronomy;
use BKuhl\BibleCSB\Book\Ecclesiastes;
use BKuhl\BibleCSB\Book\Ephesians;
use BKuhl\BibleCSB\Book\Esther;
use BKuhl\BibleCSB\Book\Exodus;
use BKuhl\BibleCSB\Book\Ezekiel;
use BKuhl\BibleCSB\Book\Ezra;
use BKuhl\BibleCSB\Book\FirstChronicles;
use BKuhl\BibleCSB\Book\FirstCorinthians;
use BKuhl\BibleCSB\Book\FirstJohn;
use BKuhl\BibleCSB\Book\FirstKings;
use BKuhl\BibleCSB\Book\FirstPeter;
use BKuhl\BibleCSB\Book\FirstSamuel;
use BKuhl\BibleCSB\Book\FirstThessalonians;
use BKuhl\BibleCSB\Book\FirstTimothy;
use BKuhl\BibleCSB\Book\Galatians;
use BKuhl\BibleCSB\Book\Genesis;
use BKuhl\BibleCSB\Book\Habakkuk;
use BKuhl\BibleCSB\Book\Haggai;
use BKuhl\BibleCSB\Book\Hebrews;
use BKuhl\BibleCSB\Book\Hosea;
use BKuhl\BibleCSB\Book\Isaiah;
use BKuhl\BibleCSB\Book\James;
use BKuhl\BibleCSB\Book\Jeremiah;
use BKuhl\BibleCSB\Book\Job;
use BKuhl\BibleCSB\Book\Joel;
use BKuhl\BibleCSB\Book\John;
use BKuhl\BibleCSB\Book\Jonah;
use BKuhl\BibleCSB\Book\Joshua;
use BKuhl\BibleCSB\Book\Jude;
use BKuhl\BibleCSB\Book\Judges;
use BKuhl\BibleCSB\Book\Lamentations;
use BKuhl\BibleCSB\Book\Leviticus;
use BKuhl\BibleCSB\Book\Luke;
use BKuhl\BibleCSB\Book\Malachi;
use BKuhl\BibleCSB\Book\Mark;
use BKuhl\BibleCSB\Book\Matthew;
use BKuhl\BibleCSB\Book\Micah;
use BKuhl\BibleCSB\Book\Nahum;
use BKuhl\BibleCSB\Book\Nehemiah;
use BKuhl\BibleCSB\Book\Numbers;
use BKuhl\BibleCSB\Book\Obadiah;
use BKuhl\BibleCSB\Book\Philemon;
use BKuhl\BibleCSB\Book\Philippians;
use BKuhl\BibleCSB\Book\Proverbs;
use BKuhl\BibleCSB\Book\Psalms;
use BKuhl\BibleCSB\Book\Revelation;
use BKuhl\BibleCSB\Book\Romans;
use BKuhl\BibleCSB\Book\Ruth;
use BKuhl\BibleCSB\Book\SecondChronicles;
use BKuhl\BibleCSB\Book\SecondCorinthians;
use BKuhl\BibleCSB\Book\SecondJohn;
use BKuhl\BibleCSB\Book\SecondKings;
use BKuhl\BibleCSB\Book\SecondPeter;
use BKuhl\BibleCSB\Book\SecondSamuel;
use BKuhl\BibleCSB\Book\SecondThessalonians;
use BKuhl\BibleCSB\Book\SecondTimothy;
use BKuhl\BibleCSB\Book\SongOfSolomon;
use BKuhl\BibleCSB\Book\ThirdJohn;
use BKuhl\BibleCSB\Book\Titus;
use BKuhl\BibleCSB\Book\Zechariah;
use BKuhl\BibleCSB\Book\Zephaniah;

enum BookEnum: int
{
    case GENESIS = Genesis::ID;
    case EXODUS = Exodus::ID;
    case LEVITICUS = Leviticus::ID;
    case NUMBERS = Numbers::ID;
    case DEUTERONOMY = Deuteronomy::ID;
    case JOSHUA = Joshua::ID;
    case JUDGES = Judges::ID;
    case RUTH = Ruth::ID;
    case FIRST_SAMUEL = FirstSamuel::ID;
    case SECOND_SAMUEL = SecondSamuel::ID;
    case FIRST_KINGS = FirstKings::ID;
    case SECOND_KINGS = SecondKings::ID;
    case FIRST_CHRONICLES = FirstChronicles::ID;
    case SECOND_CHRONICLES = SecondChronicles::ID;
    case EZRA = Ezra::ID;
    case NEHEMIAH = Nehemiah::ID;
    case ESTHER = Esther::ID;
    case JOB = Job::ID;
    case PSALMS = Psalms::ID;
    case PROVERBS = Proverbs::ID;
    case ECCLESIASTES = Ecclesiastes::ID;
    case SONG_OF_SONGS = SongOfSolomon::ID;
    case ISAIAH = Isaiah::ID;
    case JEREMIAH = Jeremiah::ID;
    case LAMENTATIONS = Lamentations::ID;
    case EZEKIEL = Ezekiel::ID;
    case DANIEL = Daniel::ID;
    case HOSEA = Hosea::ID;
    case JOEL = Joel::ID;
    case AMOS = Amos::ID;
    case OBADIAH = Obadiah::ID;
    case JONAH = Jonah::ID;
    case MICAH = Micah::ID;
    case NAHUM = Nahum::ID;
    case HABAKKUK = Habakkuk::ID;
    case ZEPHANIAH = Zephaniah::ID;
    case HAGGAI = Haggai::ID;
    case ZECHARIAH = Zechariah::ID;
    case MALACHI = Malachi::ID;
    case MATTHEW = Matthew::ID;
    case MARK = Mark::ID;
    case LUKE = Luke::ID;
    case JOHN = John::ID;
    case ACTS = Acts::ID;
    case ROMANS = Romans::ID;
    case FIRST_CORINTHIANS = FirstCorinthians::ID;
    case SECOND_CORINTHIANS = SecondCorinthians::ID;
    case GALATIANS = Galatians::ID;
    case EPHESIANS = Ephesians::ID;
    case PHILIPPIANS = Philippians::ID;
    case COLOSSIANS = Colossians::ID;
    case FIRST_THESSALONIANS = FirstThessalonians::ID;
    case SECOND_THESSALONIANS = SecondThessalonians::ID;
    case FIRST_TIMOTHY = FirstTimothy::ID;
    case SECOND_TIMOTHY = SecondTimothy::ID;
    case TITUS = Titus::ID;
    case PHILEMON = Philemon::ID;
    case HEBREWS = Hebrews::ID;
    case JAMES = James::ID;
    case FIRST_PETER = FirstPeter::ID;
    case SECOND_PETER = SecondPeter::ID;
    case FIRST_JOHN = FirstJohn::ID;
    case SECOND_JOHN = SecondJohn::ID;
    case THIRD_JOHN = ThirdJohn::ID;
    case JUDE = Jude::ID;
    case REVELATION = Revelation::ID;
} 